### ISSUE TITLE
RabbitMQ template throws "The system cannot infer the transport information from the rabbitmq:/SalesOrderQueue..." error when trying to send a message

### ISSUE THREAD

**Issue by wx-yz** [wso2/devstudio-tooling-ei#1000]
**Description:**
Following error is thrown in the console when trying to execute the inbuilt RabbitMQ template. Followed instructions to enable rabbitmq sender in <INTSTUDIO_HOME>/runtime/microesd/conf/axis2/axis2.xml but this file seems to be regenerated every time we right click and say Export Project Artifacts and Run.

There's another file in backups but that doesn't seem to be effective. Or it seems like current changes are being copied to backups folder and then generate a fresh config from somewhere. Maybe I've missed an instruction?

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio latest

![image](https://user-images.githubusercontent.com/57770159/82969166-dae20880-9f83-11ea-822a-4c64d210f2c0.png)

**OS, DB, other environment details and versions:**    
Windows 10

**Comment by prabushi** [comment]
@wx-yz In WSO2 MI, we need to configure all the transport configurations in  MI_HOME/conf/deployment.toml file, as described in [here](https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/brokers/configure-with-rabbitMQ/). Can you make sure all the rabbitMQ transport configurations defined in toml are correct? Because it seems the mentioned error comes at the runtime due to a configuration mismatch.

**Comment by wx-yz** [comment]
Can we either modify the template help text to point to this doc or create a URL? Template Guide doc is saying something different,

![rabbitmq-help-text](https://user-images.githubusercontent.com/57770159/83469052-6e5b8380-a433-11ea-9df4-e46e536932ce.png)

**Comment by dilee** [comment]
> Can we either modify the template help text to point to this doc or create a URL? Template Guide doc is saying something different,
> 
> ![rabbitmq-help-text](https://user-images.githubusercontent.com/57770159/83469052-6e5b8380-a433-11ea-9df4-e46e536932ce.png)

Fixed this in https://github.com/wso2/devstudio-tooling-esb/pull/1160
