### ISSUE TITLE
Integration Studio embedded micro-integrator server fail on return data service details

### ISSUE THREAD

**Issue by Mondongo-cl** [wso2/devstudio-tooling-ei#1005]
**Description:**

mi CLI tool fails when using show command over data service objects, in the micro-integrator runtime side I get a 
```
java.lang.NoClassDefFoundError: org/wso2/carbon/dataservices/core/DBUtils at 
org.wso2.micro.integrator.management.apis.DataServiceResource.populateDataServiceList
(DataServiceResource.java:94)
```
in the command side, the CLI tool (mi) keep waiting and then show an error message
```
mi: Unable to connect to https://localhost:9164/management/data-services
Execute with --verbose to see detailed info.
```

As a workaround, I copy the latest version of the micro-integration in the runtime\microesb, this solves the issue.

**Suggested Labels:**
runtime, micro-integrator, tooling,

**Suggested Assignees:**

**Affected Product Version:**

WSO2 Integration Studio 7.0.2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- download the 7.0.2 version of integrator studio (current)
- create a new project
- add a data service
- ensure the value od DenableManagementApi VM parameter is set to true
- configure and deploy the project into built-in micro-integrator
- open a command line window (run cmd)
- login into micro-integrator server using mi CLI tool
- execute the command to list the deployed data services (mi data service show)

**Related Issues:**

**Comment by prabushi** [comment]
@Mondongo-cl 
Thanks for reporting the issue. This is due to an issue identified with the embedded WSO2 MI packed with Integration Studio 7.0.2. We have packed the latest WSO2 MI 1.2.0-alpha distribution with the Integration Studio 7.1.0-alpha release (Related git issue: https://github.com/wso2/devstudio-tooling-ei/issues/887).
