### ISSUE TITLE
Integration Studio template fonts too small in Linux even after setting -Dswt.autoScale=200

### ISSUE THREAD

**Issue by wx-yz** [wso2/devstudio-tooling-ei#1006]
**Description:**
Default templates and icons looks really small in Linux (Gnome). Gnome desktop is running at display scaled to 200%. Here's what Integration Studio looks like just after unzip and run.

![dev-studio-default](https://user-images.githubusercontent.com/57770159/83468350-5d117780-a431-11ea-8fad-a2eb6c5ceba5.png)

Then I modified IntegrationStudio.ini and set -Dswt.autoScale=200. This made inbuilt icons bigger. Template fonts remains small and unreadable. Here's a picture after setting -Dswt.autoScale=200

![dev-studio-200-scaling](https://user-images.githubusercontent.com/57770159/83468402-8205ea80-a431-11ea-95a4-1f4424c81cd2.png)

How can I set scaling so that everything looks consistent? Tried removing -Dswt.autoScale property but it doesn't seem to change anything.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio latest
![devstudio-version](https://user-images.githubusercontent.com/57770159/83468770-b037fa00-a432-11ea-98ab-c2441754aa11.png)

**OS, DB, other environment details and versions:**    
Ubuntu 20.04

**Comment by prabushi** [comment]
Related issue https://github.com/wso2/devstudio-tooling-ei/issues/958

**Comment by prabushi** [comment]
This issue was observed on Linux 20 as the display scaling with high resolution was not picked up by the internal browser in Eclipse. However, we have done some modifications to make the fonts more clearer with the new getting started page revamp.

**Comment by wx-yz** [comment]
I did a fresh install and then ran the update tool to install latest updates. I still see the template fonts too small. Here's a screenshot.

![image](https://user-images.githubusercontent.com/57770159/93915297-ac1f3900-fcbc-11ea-8a5e-4461ebd40d54.png)

Here's my updated version numbers,

![image](https://user-images.githubusercontent.com/57770159/93915454-e983c680-fcbc-11ea-8bc2-fefb0aeb9679.png)
