### ISSUE TITLE
Implement All Functionalities to Create and Manage Topics via Tooling

### ISSUE THREAD

**Issue by praneesha** [wso2/devstudio-tooling-ei#101]
**Description:**
Currently, we can't create and manage Topics via WSO2 ESB/EI Tooling, and it can be done only via the Management Console.

We need to add these functionalities to WSO2 EI Tooling.

For more information, please refer the email[1] and [2].

[1] [EIP] - Creating Topics for the Publish Subscribe EIP
[2] https://wso2.org/jira/browse/DOCUMENTATION-3570

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
Topic concepts in ESB is no longer used. We have better approaches to achieve pub-sub EIP model. 
So implementing tooling for this is not required.
