### ISSUE TITLE
Duplicate Sub-Project Name in Create Integration Project Wizard

### ISSUE THREAD

**Issue by Asitha** [wso2/devstudio-tooling-ei#1019]
Steps to reproduce

1. Open up Integration Project Creation Wizard (From dashboard or context menu)
1. Provide an integration project name
1. Untick "Wrap children projects.....". This will update the ESB config project name to Integration Project Name
1. tick the  "Wrap children projects....." again. This doesn't update the config project name or give any warning
1. Hit finish. The project is partially created without the config project with errors.

This is the same for other project types as well. Needs to add a validation to all the subproject names to check whether there are any duplicate project names.

**Comment by prabushi** [comment]
Also, we need to check if any of the project name is empty before creating the projects.
