### ISSUE TITLE
Add QoS Parameter support through text entry to Developer Studio

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#102]
**Description:**
Currently rabbitmq.channel.consumer.qos property is supported only through a registry entry. This should also be supported through a text entry too.

ex :-
Currently supported 
`<parameter key="conf:/rabbitmq.channel.consumer.qos.property" name="rabbitmq.channel.consumer.qos"/>`

Should support
`<parameter name="rabbitmq.channel.consumer.qos">1</parameter>`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
This Parameter is missing from Management Console Even.
Created an issue to track this https://github.com/wso2/product-ei/issues/2431.
