### ISSUE TITLE
'ESB Config Project' or 'Config Project'

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/devstudio-tooling-ei#1025]
**Description:**

Should it be **ESB Config Project** or **Config Project**? Currently, the **New Integration Project** wizard uses 'ESB Config Project'. However, under **Miscellaneous**, it says **Config Project**.  Also, the icon reads as **ESB**.

Shall we make this consistent? I suggest **Config Project** because we are no longer referring ESB terms.

**Suggested Labels:**
UI

**Affected Product Version:**
7.1.0

**Comment by prabushi** [comment]
Remove the name 'Project' from the children of the integration project and make them sub-components. Rename as the following.
- ESB configs
- Registry resources
- Docker exporter
- Kebernetes exporter
- Connector exporter
