### ISSUE TITLE
Refactor connector properties view code

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1034]
**Description:**
Refactor code merged with https://github.com/wso2/devstudio-tooling-esb/pull/1150

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1216
