### ISSUE TITLE
[Improvement] Add check box to run cipher tool in docker projects

### ISSUE THREAD

**Issue by sachithKay** [wso2/devstudio-tooling-ei#1041]
**Description:**
- Current config mapper implementation accepts a executeCiperTool property, which will decide whether or not the cipher tool has to be run before creating the image. 
- We need to add a checkbox of some sort where the user can configure in order to set the above mentioned property in docker/k8 projects.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-platform/pull/281
