### ISSUE TITLE
Endpoints lost while switching from Design view to Source view while the config is being loaded

### ISSUE THREAD

**Issue by evanthika** [wso2/devstudio-tooling-ei#105]
**Description:**
Opening Proxy services, Sequences from EI tooling and clicking on _Source View_ while the _Design View_ is being loaded all the endpoints will be deleted automatically. Once the _Source View_ is loaded (partially), assume we do some changes and save, it would save the config without the endpoints as they were lost while the config was being loaded.

**Suggested Labels:**
devstudio, tooling

**Suggested Assignees:**
Prabushi Samarakoon

**Affected Product Version:**
Dev-Studio Tooling - EI

**Steps to reproduce:**
1. Open a Proxy Service/Sequence from Dev studio.
2. While the config is being loaded, click on the _Source View_.
3. The endpoints you have added from the _Design View_ will not be loaded.
4. If we change the config from the source view and save, the endpoints etc will be all gone.

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2460
