### ISSUE TITLE
Add text area support for connector parameters

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1052]
**Description:**
Add text area support for connector parameters in the new properties view to support params like email content, etc.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1216
