### ISSUE TITLE
Update data service editor theme

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1059]
**Description:**
Update the data service editor theme, which is more compatible with the existing theme.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-dss/pull/206
