### ISSUE TITLE
Dev-studio code base needs to be refactored.

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/devstudio-tooling-ei#106]
When adding or removing parameters or attributes of an element in EI and auto-generating the required code, some other lines of codes that are not relevant are getting either added or removed. Possible reasons for this may be is that when adding or removing attributes or properties in the past, we had committed some part of code and missed some other or hadn't put  'generated NOT' when modifying generated code.  We need to analyze what attributes and properties each element in the EI has and generate a stable version of auto-generated code.

**Comment by sohaniwso2** [comment]
Can you please provide a sample code which illustrates this issue?

**Comment by ThishaniLucas** [comment]
One such example is that in the commit https://github.com/wso2/devstudio-tooling-esb/pull/290/commits/72083b9498ba14dc9d30ba211252d40698a7bd8f, I had to manually change the cache mediator related values in the EsbPackageImpl.java

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2461
