### ISSUE TITLE
Improve the docker push wizard

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1061]
**Description:**
Add the information to identify as to what image, which tag is being pushed to which remote registry at this wizard.
![docker-push](https://user-images.githubusercontent.com/5234623/84433436-e869e480-ac4b-11ea-93ee-28b3ef8bebf5.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Duplicate issue https://github.com/wso2/devstudio-tooling-ei/issues/1026, and fixed in https://github.com/wso2/devstudio-tooling-platform/pull/282
