### ISSUE TITLE
Cannot switch to design view when validate mediator is added to sequence

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#108]
**Description:**
When a validate mediator is added to sequence we cannot switch to design view afterwards. And the error message is given below. But when a schema is added to the config this error doesn't occur.

![selection_031](https://user-images.githubusercontent.com/3378323/34561911-113371de-f172-11e7-9ac7-105e7378b1d0.png)

**Steps to reproduce:**
1. Create new sequence
2. Add validate mediator
3. Switch to source view and switch back to design view.

**Comment by sohaniwso2** [comment]
Validate mediator requires a 'Schema key' which specifies the key for the schema location and also we must add 'fail' sequence as a child of validate mediator using the "Fault" mediator. Those two are mandatory fields for the validate mediator and that is why it gives this syntax error.

Workaround: 
After drag and drop the validate mediator to the graphical editor, we can configure the schema key using the properties view to solve this issue. Also need to add a Fault mediator from the Palette into the Validate Mediator
**We need to properly validate this in future**

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2462
