### ISSUE TITLE
Improve required parameters in the new connector view

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1081]
**Description:**
Improve the required parameters in the new connector properties view by adding a '*' for the required field labels. Furthermore, we should improve the functionality of the error notification on the top of the properties view to update according to the user input.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1216
