### ISSUE TITLE
Throwing error while running test cases from DevStudio if home directory contain spaces

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/devstudio-tooling-ei#1087]
The following error occur while running test cases if DevStudio home path contains spaces for a directory name (ex C://Users/example/micro integrator/IntegrationStudio/runtime).
```
"Unknown lifecycle phase "integrator\IntegrationStudio\runtime\microesb\bin\micro-integrator.bat". You must specify a valid lifecycle phase or a goal in the format"
```

**Comment by sajithaliyanage** [comment]
Fixed https://github.com/wso2/devstudio-tooling-esb/pull/1180 and works in MacOs. Need to test and verify in Linux and Windows platforms.
