### ISSUE TITLE
Disable graceful shutdown in embedded Micro Integrator

### ISSUE THREAD

**Issue by arunans23** [wso2/devstudio-tooling-ei#1094]
**Description:**

We need to disable graceful shutdown in Embedded Micro Integrator, since it is used only for development purposes.
We can disable graceful shutdown with the following system property.
`-DgracefulShutdown=false`

**Affected Product Version:**
IS-7.1.0-Alpha

**Comment by arunans23** [comment]
To check the effect, invoke the following API in embedded MI.

```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/original" name="TestAPI" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <log level="full"/>
            <call>
                <endpoint>
                    <address uri="http1://www.mocky.io/v2/5ed7d60932000019d9274cb8">
                        <suspendOnFailure>
                            <initialDuration>-1</initialDuration>
                            <progressionFactor>1</progressionFactor>
                        </suspendOnFailure>
                        <markForSuspension>
                            <retriesBeforeSuspension>0</retriesBeforeSuspension>
                        </markForSuspension>
                    </address>
                </endpoint>
            </call>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence>
        </faultSequence>
    </resource>
</api>
```

And then if you try to stop MI, the following error would be thrown.

![Screenshot from 2020-06-15 18-36-49](https://user-images.githubusercontent.com/17047910/84660993-4e4db900-af37-11ea-8a52-1624dab6bb3b.png)

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-platform/pull/287/commits/1bac38a14fb477ad1922a114f9c5aa39bb843d92
