### ISSUE TITLE
[Connector] Search option for connector parameters

### ISSUE THREAD

**Issue by milindaperera** [wso2/devstudio-tooling-ei#1095]
**Description:**
$subject

To improve UX when there are large set of parameters we need to provide option to search connector parameters.

![Screenshot 2020-06-16 at 09 11 50](https://user-images.githubusercontent.com/7402364/84729557-a0332500-afb1-11ea-96c6-77af1a2a8718.png)

**Comment by milindaperera** [comment]
Related: https://github.com/wso2/devstudio-tooling-ei/issues/929

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1340
