### ISSUE TITLE
Improve UI/UX aspects of the Getting Started page

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1100]
**Description:**
Need to improve the UI/UX aspects including the icons, colors, etc. of the Getting Started page.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dilee** [comment]
Related Issues: https://github.com/wso2/devstudio-tooling-ei/issues/892
