### ISSUE TITLE
Implement a way to hide certain templates from being displayed in pattette

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#1106]
**Description:**

When we are developing WSO2 EI connector logic, sometimes we need to keep templates that is reusable across the operations. They are like `private` templates. They should not appear in the palette. 

If we remove such templates from component.xml, they are not accessible as per @dinuish94. Thus we need to device a way to hide them. I vote we can have an attribute for component tag in component.xml files. 

<component name="runQuery" visibility="false">
            <file>runQuery.xml</file>
            <description>Execute query.</description>
</component>

**Comment by prabushi** [comment]
Duplicate issue https://github.com/wso2/devstudio-tooling-ei/issues/1104
