### ISSUE TITLE
[UX]Templates need to be displayed in a better way

### ISSUE THREAD

**Issue by samgnaniah** [wso2/devstudio-tooling-ei#1129]
When Integration Studio loads up and I make it full-screen, I cannot at-a-glance see which templates we have. The names are too long and do not wrap to fit the template icon/box. 

![image](https://user-images.githubusercontent.com/19791901/85830918-05092f00-b7ab-11ea-8fe6-002f88087e9f.png)

On the other hand, when Integration Studio is not in full-screen mode, I can see the names of the templates, but the boxes are then too big and I have to scroll a lot to see what we have to offer.

![image](https://user-images.githubusercontent.com/19791901/85830857-ed31ab00-b7aa-11ea-94a9-32873f926f36.png)

Once a project is created, the templates are displayed on the right. However, the display has some glitch as the first template gets cut off from the top. This is in OSX.

![image](https://user-images.githubusercontent.com/19791901/85831649-3afae300-b7ac-11ea-8236-d908ac2eff06.png)

Can we come up with better UX for displaying the available templates?

**Comment by prabushi** [comment]
Fixed with new getting started page revamp effort.
