### ISSUE TITLE
Incorrect InputType/outputType is set for data mapper

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#113]
**Description:**
When we try to map JSON to CSV using a data mapper, inputType/outputType is set as "XML" for both cases. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create a data mapper to map JSON to CSV using the attached configuration. inputType/outputType is getting set as XML at synapse source.
[datamapper-issue.zip](https://github.com/wso2/devstudio-tooling-ei/files/1630353/datamapper-issue.zip)

**Related Issues:**
This issue should be tested with the fix form the issue, https://github.com/wso2/devstudio-tooling-ei/issues/112

**Comment by prabushi** [comment]
As a workaround for this issue, we need to manually set the inputType/outputType for the datamapper at the properties pane.

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2475
