### ISSUE TITLE
Integration Studio 7.0.2 json eval not working in connector parameter expression window

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/devstudio-tooling-ei#1131]
**Description:**

In integration studio 7.0.2 when configuring connector parameters from json-eval, the mediation flow seems to get deleted. 

![Screenshot from 2020-06-30 10-44-31](https://user-images.githubusercontent.com/5234677/86088213-7efb2a00-bac3-11ea-80aa-b690f76d26af.png)

**Suggested Labels:**

Bug

**Suggested Assignees:**

**Affected Product Version:**
7.0.2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Fixed for the latest with https://github.com/wso2/devstudio-tooling-ei/issues/1001
