### ISSUE TITLE
Action buttons are too small in Docker Exporter POM Editor

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/devstudio-tooling-ei#1152]
**Description:**
![Screenshot (27)](https://user-images.githubusercontent.com/25482980/86716401-c7c05f00-c03e-11ea-86d8-f8cdbcb5882c.png)

**OS, DB, other environment details and versions:**    Windows

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-ei/issues/1202
