### ISSUE TITLE
Property view becomes unclear when scrolling

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/devstudio-tooling-ei#1155]
**Description:**
![Screenshot (31)](https://user-images.githubusercontent.com/25482980/86751641-6effbf00-c05c-11ea-8e57-d1f4a353c7fb.png)

**OS, DB, other environment details and versions:**    Windows

**Steps to reproduce:**
1. Create a File Inbound Endpoint.
2. Select the property view and scroll.

**Comment by rosensilva** [comment]
Fixed in the latest 7.2.0 release
