### ISSUE TITLE
UI overlapped in Deployed Services tab

### ISSUE THREAD

**Issue by tharakamd** [wso2/devstudio-tooling-ei#1161]
**Description:**

After running a project in Integration Studio, the Monitoring Dashboard card is appearing in the Deployed Services tab. But it appears on top of the previous card.

![image](https://user-images.githubusercontent.com/8156185/86756561-18947f80-c060-11ea-90a8-70fefbb384ab.png)

**OS, DB, other environment details and versions:**    
OS - Windows 10 Pro

**Steps to reproduce:**
- Create a new Integration project in Integration Studio
- Run project using "Export project artifacts and run"
- Click on "Deployed Services" tab

**Comment by sajithaliyanage** [comment]
Fixed in -
https://github.com/wso2/devstudio-tooling-esb/pull/1286
https://github.com/wso2/devstudio-tooling-esb/pull/1288
https://github.com/wso2/devstudio-tooling-esb/pull/1292
