### ISSUE TITLE
API handlers cannot be added via design view

### ISSUE THREAD

**Issue by milanperera** [wso2/devstudio-tooling-ei#117]
**Description:**
In Dev Studio tool, there's no any UI available to add handlers to a particular API. However, developers still can add handlers via source view.

**Affected Product Version:**
EI 6.2.0

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-3395

**Comment by prabushi** [comment]
Even at the server, we cannot add handlers via the design view of the management console. But still we support handlers at WSO2 EI https://docs.wso2.com/display/EI610/Securing+APIs

Do we need to add handler support for design view of the developer studio as well?

**Comment by sohaniwso2** [comment]
In the design view we display the resources in the API and the properties view is associated with each resource. API Handlers are added in the API level and not in resource level hence there is a limitation in viewing those in the graphical view. 

The properties related to API (hostname, port etc) are added at the time of creating the API via the API creation wizard, and if we want to change the values we need to edit the source view. Similarly we can allow users to add the handlers in the creation wizard at the time of creating the API, and later change the values in the source view if needed

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2463
