### ISSUE TITLE
Update icons on the templates

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1176]
**Description:**
Update icons on the sample templates (depending on their category)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dilee** [comment]
Categories:

- Services
- Mediation Patterns
- Message Transformation
- Error Handling
- Unit Testing
- SaaS Integrations
- Database Integration
- Messaging
- Auth and User Management
- Miscellaneous
