### ISSUE TITLE
Replace the occurrences of certain words

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1178]
**Description:**
Replace [these](https://github.com/wso2/wso2.github.io/blob/master/words_matter.md) words on the tooling repos.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Checked the following repositories for the words,
developer-studio
devstudio-tooling-bps
devstudio-tooling-dss
devstudio-tooling-ei
devstudio-tooling-esb
devstudio-tooling-platform

No occurrences were found in the UI of the integration studio
