### ISSUE TITLE
API versioning support is not provided in tooling

### ISSUE THREAD

**Issue by milanperera** [wso2/devstudio-tooling-ei#118]
**Description:**
EI tooling does not support adding API version when creating API definition either from design view or source view.

**Affected Product Version:**
EI-6.2.0

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4267

**Comment by prabushi** [comment]
Related carbon-mediation changes https://github.com/wso2/carbon-mediation/pull/959/files
