### ISSUE TITLE
Folder shown twice when a project is imported inside Maven Multi module

### ISSUE THREAD

**Issue by arunans23** [wso2/devstudio-tooling-ei#1185]
**Description:**

If you try to import a Project (HelloWorldTemplateCompositeApplication) inside a Maven multi module, the folder is shown twice. (With icon and without icon)
<img width="287" alt="Screenshot 2020-07-09 at 15 42 35" src="https://user-images.githubusercontent.com/17047910/87027579-fedb6f80-c1fa-11ea-928f-113c0bde6ca2.png">

**Affected Product Version:**
IS 7.1.0-beta

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/developer-studio/pull/228, https://github.com/wso2/devstudio-tooling-platform/pull/339, https://github.com/wso2/devstudio-tooling-esb/pull/1307/commits/a12bba651fa123ae3cd2587683be1793c9b76eb8 and https://github.com/wso2/devstudio-tooling-dss/pull/211
