### ISSUE TITLE
Add table functionality to new properties view

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#1192]
**Description:**
Add table functionality to the new properties view of modules. This is to support connectors with lots of operations (eg: fhir).

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1343
