### ISSUE TITLE
Dropdown list coming with new UI theme has become unreadable

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#121]
**Description:**
The dropdown list shown with new UI has come in a grey background with grey text. Can only read properly when we move over the dropdown elements.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
Can you please provide a screen shot or elaborate more about this?

**Comment by sohaniwso2** [comment]
This is fixed in EI Tooling 6.3.0
