### ISSUE TITLE
Connector parameters search feature

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/devstudio-tooling-ei#1252]
**Description:**
Currently there is no way to search the connector parameters in the integration studio connector parameter configuration view. 

**Suggested Labels:**
New Feature

**Comment by shyamir** [comment]
Pull request for the implementation
https://github.com/wso2/devstudio-tooling-esb/pull/1340


> **Description:**
> Currently there is no way to search the connector parameters in the integration studio connector parameter configuration view.
> 
> **Suggested Labels:**
> New Feature
