### ISSUE TITLE
[Feature] Bulk connectors import to the integration project

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/devstudio-tooling-ei#1260]
**Description:**
currently connectors can be imported one at a time to the integration project. This feature will help to import multiple connectors to the workspace from the file browser. 

**Suggested Labels:**
New feature

**Comment by shyamir** [comment]
Pull request for the implementation
https://github.com/wso2/devstudio-tooling-esb/pull/1346

> **Description:**
> currently connectors can be imported one at a time to the integration project. This feature will help to import multiple connectors to the workspace from the file browser.
> 
> **Suggested Labels:**
> New feature
