### ISSUE TITLE
Configure release builder for Developer Studio 

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#127]
**Description:**
Tasks to carryout for the release builder

1. Configure jar signing process with the weekly builder
2. Configure and test distribution installation with maven build
3. Test final pack signing

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
Need to test final pack signing

**Comment by sohaniwso2** [comment]
Fixed
