### ISSUE TITLE
In DB Lookup mediator, issue in downloading JAR library from server

### ISSUE THREAD

**Issue by Thilinika** [wso2/devstudio-tooling-ei#1287]
**Description:**
When using the DBLookup mediator, for setting up database configuration there are two options to add JAR libraries. When using the get from server option, it shows the progress of the download in a popup window, but after that when try to test the connection, it  gives the message “Please download or browse driver”.

![Screenshot from 2020-10-08 20-38-32](https://user-images.githubusercontent.com/33649582/95485176-00aa0000-09af-11eb-8db5-475770e8c946.png)
 
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Fixed in the latest release
