### ISSUE TITLE
Connector loading gets stuck with new ui schema

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/devstudio-tooling-ei#1290]
**Description:**
Currently, connector view gets stuck in the integration studio when there are significant number of connector parameters(i.e: >500) for the new ui json schema. 

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
fixed: https://github.com/wso2/devstudio-tooling-esb/pull/1359
