### ISSUE TITLE
Add WSO2 EI 6.2.0 for Server list

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#131]
**Description:**
Currently we only have up to ESB 4.x.x to EI 6.1.0. 
EL 6.1.1 is also not available in the list.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Try to add a new server and cannot find EI 6.2.0 in the server list

**Related Issues:**

**Comment by sohaniwso2** [comment]
This needs to be handled properly to list all available EI servers

**Comment by sohaniwso2** [comment]
Fixed at https://github.com/wso2/devstudio-tooling-ei/commit/226b1941b2bc29168da229f98d90e3f956273c42
