### ISSUE TITLE
Generate Proxy Service using WSDL file - Using WSDL url does not work

### ISSUE THREAD

**Issue by isudana** [wso2/devstudio-tooling-ei#1317]
**Description:**

When WSDL url is given Service name is not getting populated.

<img width="593" alt="Screenshot 2020-11-25 at 14 25 54" src="https://user-images.githubusercontent.com/748819/100204948-81569880-2f2a-11eb-909a-3cb1779224ef.png">

Using Local WSDL file option works properly.

**Affected Product Version:**
IS 7.2.0 Beta

**OS, DB, other environment details and versions:**    
macOS Catalina

**Comment by arunans23** [comment]
Currently, URLValidator does not accept localhost as a valid URL. As a workaround, we can provide the URL as `http://127.0.0.1:8280/services/Version?wsdl`. It has been fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1381
