### ISSUE TITLE
[Doc] Update "New Server" creation wizard docs 

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#132]
**Description:**
"server runtime environment" element is not available in EI Tooling Under "New Server" wizard. Need to update images of the link,   
https://docs.wso2.com/display/EI600/Running+WSO2+Enterprise+Integrator+via+Tooling
according to the current pack.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Updated the "Running WSO2 Enterprise Integrator via Tooling" section in [1] with the correct instructions and screenshots.

[1] https://docs.wso2.com/display/EI6xx/Running+the+Product#RunningtheProduct-RunningWSO2EnterpriseIntegratorviaTooling
