### ISSUE TITLE
[Doc] Update EI 6.2.0 tooling images

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#133]
**Description:**
Update EI 6.2.0 Tooling images according to the new UI changes. Since we have revamped the design flow with new icons and colors, most of the images/wizards at tooling documentation has to be updated according to the new changes.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/77
https://github.com/wso2/devstudio-tooling-ei/issues/91

**Comment by praneesha** [comment]
Updated all Tooling screenshots in [1] for WSO2 EI 6.2.0.

[1] https://docs.wso2.com/display/EI6xx/Tutorials
