### ISSUE TITLE
Undo and Redo functionalities are not working in v7.2.0-Beta

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/devstudio-tooling-ei#1333]
**Description:**
Please note $subject. Mentioned functionalities are now working in all the editors both **design** and **source** views except the swagger editor. 

**Suggested Labels:**
Type/Bug

**Relates To:**
https://github.com/wso2/devstudio-tooling-ei/issues/1321
https://github.com/wso2/devstudio-tooling-ei/issues/1329

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-dss/pull/217 and https://github.com/wso2/devstudio-tooling-dss/pull/217
