### ISSUE TITLE
[Improvement] Generate a proxy service with a WSDL

### ISSUE THREAD

**Issue by arunans23** [wso2/devstudio-tooling-ei#1334]
**Description:**

In Integration Studio, currently, there is a feature to generate REST API with Swagger. Similarly, it is better to implement a feature to generate proxy services with a WSDL definition.

**Comment by sajithaliyanage** [comment]
Fixed in:
https://github.com/wso2/devstudio-tooling-esb/pull/1368
https://github.com/wso2/devstudio-tooling-esb/pull/1369
