### ISSUE TITLE
Missing WS-policy descriptive images

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#134]
**Description:**
Descriptive images for following ws-policies are not shown when clicked on the button on left corner of respective policy.
1. Client authenticates with SAML 2.0 protection token, Symmetric Key, X509 Certificate by the Service
2. Client authenticates with SAML 1.0 protection token, Symmetric Key, X509 Certificate by the Service
3. Sign and Encrypt - X509 Authentication - SAML 2.0 Token Required as Supporting
4. Sign and Encrypt - X509 Authentication - SAML 1.1 Token Required as Supporting

![policy](https://user-images.githubusercontent.com/5234623/36829456-4a87067c-1d45-11e8-9386-aa481a730735.png) 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
Images for scenario 17-20 are not yet designed hence disabled the image buttons for now. The images will be available in a future release

![policyeditor](https://user-images.githubusercontent.com/6566181/37089571-00a0fdec-2227-11e8-9ec4-5b8d74cb94d3.png)

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2445
