### ISSUE TITLE
Missing wsdl publishing for proxy services

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#135]
**Description:**
WSDL publishing option is missing at the proxy services creation wizard. However we can edit and save publishWSDL from source view.
https://docs.wso2.com/display/ESB490/Publishing+a+WSDL#PublishingaWSDL-Specifyin-line

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
reducing the priority as we have a workaround

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2444
