### ISSUE TITLE
[Doc] Add API Version and Version type

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#159]
**Description:**
Add API version and version type introduction for the API creation wizard.

[1] - https://docs.wso2.com/display/EI620/Working+with+APIs+via+Tooling

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Updated the following in [1] to include version and version type:

- Step 4 under the "Creating a new API" section
- Step 4 under the "Adding APIs" section

[1] https://docs.wso2.com/display/EI6xx/Creating+a+REST+API
