### ISSUE TITLE
[Doc] Update EI 6.2.0 server screenshots

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#160]
**Description:**
Replace [1] with EI 6.2.0 server screenshots. We have replaced EI 6.1.1 server with 6.2.0 for 6.x.x series.

[1] - https://docs.wso2.com/display/EI620/Running+WSO2+Enterprise+Integrator+via+Tooling 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This page is removed when docs were restructured for WSO2 EI 6.2.0. Instead, the new screenshots are updated under the "Running WSO2 Enterprise Integrator via Tooling" section in [1].

[1] https://docs.wso2.com/display/EI6xx/Running+the+Product
