### ISSUE TITLE
Cache Mediator property pane does not update for collector=true

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#166]
**Description:**
Cach mediator property pane dose not update if we set collector=true. However, source view update correctly according to the collector value.
![cache](https://user-images.githubusercontent.com/5234623/37887841-b4de1ea2-30e1-11e8-9f55-1169e680300b.png)
```
        <inSequence>
            <cache collector="true"/>
        </inSequence>
```
Furthermore, if we close the artifact window (eg: API window that contains the cache mediator) and switch collector value to true and false, cache property pane is getting updated correctly. This issue only occurs at the first time when we create the cache mediator.
![cache2](https://user-images.githubusercontent.com/5234623/37887938-399665f0-30e2-11e8-91bf-a8fdf0906805.png)
 
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
The property view needs to be compatible with the management console to include the "Cache Type"  instead of Collector Boolean value.

**Comment by sohaniwso2** [comment]
Fixed
