### ISSUE TITLE
Unable to switch back to design with validate mediator

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#173]
**Description:**
Add a validate mediator and save it, then switch to source view. Then when we try to switch back to design view, there is a pop up window with a synapse validation error, and cannot switch back to design view.

Only option is to remove the validate mediator from the source view and switch to design view.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.2.0

**OS, DB, other environment details and versions:**    
Linux

**Steps to reproduce:**
1. Add a validate mediator to an empty proxy service
2. Save the configuration
3. Switch to source view and try to switch back to design view

**Related Issues:**

**Comment by sohaniwso2** [comment]
Fixed at https://github.com/wso2/devstudio-tooling-esb/commit/0deb2a5d231abecdc9bf23a4ecbee6af74c0e832
