### ISSUE TITLE
Add cache-schema attribute for validate mediator

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#175]
**Description:**
Add cache-schema attribute support for validate mediator property pane which was introduced in https://github.com/wso2/wso2-synapse/pull/1031

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
Fixed
