### ISSUE TITLE
Printing artifact graphically

### ISSUE THREAD

**Issue by eapereira** [wso2/devstudio-tooling-ei#184]
Hello folks, is there any way to print an artifact graphically using WSO2 Tooling?

Regards,
LottaLava

**Comment by sohaniwso2** [comment]
Hi LottaLava,

Could you please elaborate more on your requirement? Do you want to get a printout of the created synapse configuration?

**Comment by eapereira** [comment]
Yes, I'd like to print the synapse graphic as eclipse/wso2 studio show in the view.

http://2.bp.blogspot.com/-0jVH_e8iWP8/UmaAIkiMEuI/AAAAAAAAANc/DWwiG0TJ1x0/s1600/cloudConnector20_.png

**Comment by sohaniwso2** [comment]
As WSO2 EI tooling uses to develop and deploy the artifacts for WSO2 EI server, printing the synapse configuration is not possible at the moment.

**Comment by sohaniwso2** [comment]
I'm closing the issue as per the above comment. Please reopen if you have issues
