### ISSUE TITLE
[Kafka Inbound] Content Type limited to application/xml and application/json

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/devstudio-tooling-ei#198]
**Description:**
Kafka inbound endpoint content type property only allow selecting application/xml and application/json. We should provide an option to define validate content type here. Even if we edit the content type in source view, it reset to application/json.

![screenshot from 2018-06-06 10-58-21](https://user-images.githubusercontent.com/3735291/41019371-ef87a10e-697b-11e8-8f52-346e73b33e96.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
All versions.

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
Fixed
