### ISSUE TITLE
Unable to add parameter to sequence template

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/devstudio-tooling-ei#199]
**Description:**
When adding the template parameter for a sequence template via Properties pannel with the name 'name', the parameter is not getting added to the config. Even though we try to add it directly via source view, the parameter with the name 'name' is not persisting when switched to design view. But when we use a different name for the parameter, it's working fine.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
This is not a bug as we cannot add 'name' or 'uri' as parameters. Please refer the below code

private void saveParameters(Template template, Collection<String> parameters) {
		for (TemplateParameter templateParameter :  template.getParameters()) {
			if (templateParameter != null && !(templateParameter.getName().equals("name") || templateParameter.getName().equals("uri"))) {
				parameters.add(templateParameter.getName());
			}
		}
	}
