### ISSUE TITLE
Unable to define Xquery mediator with ELEMENT type variable. 

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/devstudio-tooling-ei#205]
**Description:**
When we define an xquery mediator using the source view with ELEMENT type variable, neither the design view is not getting rendered nor the config is getting saved. Also it could be seen that when we define an xquery mediator using the design view and when the ELEMENT type variable is set using the properties panel, a default value for the variable is getting added. It seems the xquery mediator cannot be stored without a value for the variable. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
moved to product-ei at https://github.com/wso2/product-ei/issues/2440

**Comment by sohaniwso2** [comment]
Fixed
