### ISSUE TITLE
6.1.1 - Custom Mediator using POI cant add dependencies!

### ISSUE THREAD

**Issue by eapereira** [wso2/devstudio-tooling-ei#207]
Hello, I just created some custom Mediator to write spreadsheets with poi, but I having some trouble to add this dependency to my Mediator. I got java.lang.ClassNotFoundException when using POI.

**Comment by sohaniwso2** [comment]
When deploying the Mediator with third party dependencies from the .car file, WSO2 ESB uses the URLClassLoader to load the required classes.For URLClassLoader to load the classes, the dependencies should be inlined. Hence, could you please use the <Embed-Dependency> tag in the maven-bundle-plugin as below

 <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>3.5.0</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <id>bundle-manifest</id>
            <phase>process-classes</phase>
            <goals>
              <goal>manifest</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <instructions>
            <Export-Package>com.ing.modelbank.esb.mediator.phoenix</Export-Package>
            <Import-Package>*;resolution:=optional</Import-Package>
            **<Embed-Dependency>*;scope=compile|runtime;inline=true</Embed-Dependency>**
            <Embed-Transitive>true</Embed-Transitive>
          </instructions>
        </configuration>
      </plugin>

Please make sure to add the required third party dependences in the pom.xml as well

**Comment by prabushi** [comment]
You can use maven-shade-plugin or maven-assembly-plugin to bundle all the required dependencies into your class mediator.
Please refer the following for more details.

[1] - https://docs.wso2.com/display/EI650/Creating+Custom+Mediators#CreatingCustomMediators-Buildingthemediator
[2] - https://maven.apache.org/plugins/maven-shade-plugin/usage.html
[3] - https://www.mkyong.com/maven/create-a-fat-jar-file-maven-shade-plugin/ 
[4] - http://maven.apache.org/plugins/maven-assembly-plugin/

Please reopen the issue, if you are still getting any errors with your class mediator code.
