### ISSUE TITLE
[6.3.0] Spelling error in default endpoint image

### ISSUE THREAD

**Issue by mathieubouchard** [wso2/devstudio-tooling-ei#211]
**Description:**
When adding a default endpoint in a send mediator, it is written DEFALUT in the graphical image instead of DEFAULT

**Affected Product Version:**
WSO2 Enterprise Integrator Tooling 6.4.0

**OS, DB, other environment details and versions:**    
Windows 7

**Steps to reproduce:**
Create a sequence
Add a send mediator
Add a default endpoint in the send mediator

```
<send>
  <endpoint>
    <default/>
  </endpoint>
</send>
```

**Comment by Nirothipan** [comment]
Moved to https://github.com/wso2/product-ei/issues/2574
