### ISSUE TITLE
[6.3.0] Spelling error in Filter mediator

### ISSUE THREAD

**Issue by mathieubouchard** [wso2/devstudio-tooling-ei#212]
**Description:**
When using a Filter Mediator from the tooling, we can edit the *Condition Type* property. The choices are *XPath* and ***Source and Regualar Expression***. The last one should be *Source and Regular Expression*.

https://github.com/search?q=org%3Awso2+Source+and+Regualar+Expression&type=Code

**Affected Product Version:**
WSO2 Enterprise Integrator Tooling 6.3.0

**OS, DB, other environment details and versions:**    
Windows

**Comment by Nirothipan** [comment]
Moved to https://github.com/wso2/product-ei/issues/2573
