### ISSUE TITLE
Adding Tooltips to Icons

### ISSUE THREAD

**Issue by praneesha** [wso2/devstudio-tooling-ei#213]
**Description:**
In the Studio palette when we hover any item, it should give a brief description like for "Send" - "Sends a message to "defined endpoint" or new endpoint" or "validates" - "validates agains a schema or something"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
This feature is already supported in Devstudio Tooling. We can try to improve it by adding a more meaningful description there.

**Comment by prabushi** [comment]
Duplicated issue https://github.com/wso2/product-ei/issues/2454
