### ISSUE TITLE
Add a web based template dashboard

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#215]
**Description:**
Add a web based dashboard which has templates to quick start a project

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/product-ei/issues/2608
