### ISSUE TITLE
Hot-Update is not working when changes are saved

### ISSUE THREAD

**Issue by jairo-fernandez** [wso2/devstudio-tooling-ei#221]
**Description:**
I have a composite application with dependencies to a synapse project.  
I also have an EI server defined withing eclipse.  I'm able to add the composite application to the server from DevStudio and it gets deployed correctly, also I'm able to re-deploy correctly after some changes.
The problem is automatic hot-update seems not to be working at all, then when I make changes and save them, the CApp is not automatically re-deployed.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Devstudio-tooling-ei

**OS, DB, other environment details and versions:**    
Oracle JDK 1.8.0_162
Eclipse Java EE IDE for Web Developers.  (bundle downloaded)
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
OS: Windows 10, v.10.0, x86_64 / win32

**Steps to reproduce:**
Create a synapse project
Add a proxy service 
Add a property mediator to the in sequence
Add a Log mediator to log the value of the property
Create a Composite application project
Edit pom.xml and associate the recently created synapse project
Go to server's view in Java EE perspective, Add a new Server Enterprise Integrator
Ensure you select "enable hot update" check-box
Add the composite application to this server
Start the server from server's view in Eclipse
Call proxy and observe log in Console View 
Modify property value in the proxy service
Save changes
Observe Console View...   No hot update happening

**Related Issues:**

**Comment by prabushi** [comment]
@jairo-fernandez 
This is the default behavior of the Integration Studio. Only the redeploy option of the capp will deploy the new changes. (Even server start/restart will not take the new capp changes into consideration. It just starts/restarts the server with existing capps) 
When we make a change to a synapse artifact and save it, there is no way to know if this is the final version of the capp which needs to be deployed and tested. Hence, the capp redeploy option is given to the user to deploy the capp with new changes when needed.

We will be closing this issue, please feel free to reopen this for further clarification.
