### ISSUE TITLE
REST Api not updated in Carbon after deployment

### ISSUE THREAD

**Issue by ludo-21south** [wso2/devstudio-tooling-ei#239]
**Description:**
When deploying a modified REST API the old resource information is sometimes kept. So after deploying the new CAR file, all new sequences, endpoints, etc. are included but the changed REST resources are not. When copy-pasting the code from eclipse directly into carbon source view there is no error and the code works.

**Suggested Labels:**
wso2,ei,rest

**Affected Product Version:**
WSO2 EI 6.4.0
Dev Studio 4.3.0
Eclipse 2018-12

**OS, DB, other environment details and versions:**    
Ubuntu 18.04 LTS

**Steps to reproduce:**
1. Modify an existing API resource (in my case, set url-mapping to uri-template and add a variable)
2. Save and deploy CAR (by commandline or via eclipse, doesn't matter)
3. Open CAR and see the old situation still in the CAR.

Now this seems to be very consistent when working on the same API (albeit different resources).

**Comment by dakshika** [comment]
@ludo-21south  did you remove the previous CAR from the server before redeploy?

**Comment by ludo-21south** [comment]
Yes, I usually overwrite the file but just to be sure I removed it completely before redeploy. I also tried the scenario where I start the ESB before deploying and also after the deployment. Both scenario's yield the same result.

**Comment by ludo-21south** [comment]
No other suggestions? This is still an issue.

**Comment by prabushi** [comment]
@ludo-21south 
Did you notice any errors while deploying the CAR application?
Ideally, while re-deploying the CAR, deployer un-deploy all the arifacts and deploy the CAR again. Therefore, it should deploy the CAR with new changes unless there were any issues while un-deploying the old version.
Make sure, you have saved the new changes in your API before you re-deploy the CAR.
Furthermore, this can be a browser cache issue, where the new changes are not reflected in the browser. Please clean the cache and check for the changes too.

**Comment by prabushi** [comment]
@ludo-21south
We are closing this issue as we could not observe this behavior with the latest version. Please feel free to reopen this if you still face this issue.
