### ISSUE TITLE
Defining a Micro Integrator Server does not work 

### ISSUE THREAD

**Issue by robbla** [wso2/devstudio-tooling-ei#254]
When you want to define a server In Developer Studio (6.5.0) the product is not able to do that since it refers to a different version xxx.36 version of the jar rather than the xxx.38 that is in the product. 

![afbeelding](https://user-images.githubusercontent.com/11582659/56565802-78188380-65b1-11e9-9cf9-cc730503a7ee.png)

Renaming the jar file works but the process fails on the tomcat (look at the bin/bin directory)

 Missing classpath entry /opt/wso2/Desktop/wso2mi-1.0.0-m3/wso2/micro-integrator/bin/bin/tomcat-juli-7.0.85.jar

This continues with the third jar file (bin/bin/bin)  
Working with M3 of MI, m5 of EI and the dev studio version at https://medium.com/@prabushi/visual-cues-to-indicate-errors-in-wso2-enterprise-integrator-tooling-4d2dc5c1bd0

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-platform/pull/196/commits/3024bae1083139a899bbbe2cccf6fd06150c7a59
