### ISSUE TITLE
Error in the Fault mediator does not get picked up 

### ISSUE THREAD

**Issue by robbla** [wso2/devstudio-tooling-ei#255]
When using the new tooling and the possibility to get context informatie as described here  (https://medium.com/@prabushi/visual-cues-to-indicate-errors-in-wso2-enterprise-integrator-tooling-4d2dc5c1bd0), a real world scenario failed. 

Recently I reused a piece of XML code to do fault mediation. However Developer Studio did not pick up on that error in the source view. An attribute of the fault mediator that I used had an error as far as the value goes in the code-element. The value="soap11Env:Sender" does not exist anymore as one of the options of the fault mediator. When I switched back to design-view it actually replaced my value with a random (but existing) value for the code (value="soap11Env:VersionMismatch"). Making a mistake in the Log mediator category was however picked up, showing a suggestion about possible values.

![afbeelding](https://user-images.githubusercontent.com/11582659/56566839-e65e4580-65b3-11e9-8de0-3fbc92f0c26a.png)

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/product-ei/issues/3999
