### ISSUE TITLE
EI 6.1.1 - builder mediator loose "http://ws.apache.org/ns/synapse" namespace on editor

### ISSUE THREAD

**Issue by jpvadell** [wso2/devstudio-tooling-ei#30]
When I add a builder mediator appears like this. And the tool show an error and is because the element don't have the correct namespace "http://ws.apache.org/ns/synapse".
    <builder xmlns=""/>
If I correct this adding the namespace, the editor delete it again.

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/commit/bbd6e246bc75de151d00ad61ac1d67f5659c047f
