### ISSUE TITLE
[ Tooling ] [DSS]  SQL queries are changed once saved. 

### ISSUE THREAD

**Issue by Nirothipan** [wso2/devstudio-tooling-ei#315]
**Description:**

 SQL queries "formatted" are changed once saved. 
We need to verify the consitency.

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-dss/pull/151 and https://github.com/wso2/devstudio-tooling-dss/commit/f08542d0bd3b040f8e771f8cc91dfcbdce06d05f
