### ISSUE TITLE
[6.1.1]When I imported a local entry it creates an unnecessary element in Design view

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#32]
When I imported a local entry it creates an unnecessary element in Design view.

I browsed and import the below config as a local entry.

```
<?xml version="1.0" encoding="UTF-8"?><localEntry xmlns="http://ws.apache.org/ns/synapse" key="MySFConfig">
    <salesforce.init>
        <username>ushanib@gmail.com</username>
        <password>password<token></password>
        <loginUrl>https://login.salesforce.com/services/Soap/u/40.0</loginUrl>
        <blocking>false</blocking>
    </salesforce.init>
    <description/>
</localEntry>
```

I have drawn a rectangle around it in the attached screen shot

![screenshot from 2017-07-07 12-16-58](https://user-images.githubusercontent.com/12966170/27946233-643c17ca-630e-11e7-92fe-360dc526d74d.png)

**Comment by ushanib** [comment]
Can be seen when creating from the scratch as well

**Comment by sohaniwso2** [comment]
fixed at https://github.com/wso2/devstudio-tooling-esb/commit/e3f3096be512faba84720120addb2000d606b7fe
