### ISSUE TITLE
Unable to specify a FTP parameters value as a registry entry in VFS proxy.

### ISSUE THREAD

**Issue by kesavany** [wso2/devstudio-tooling-ei#335]
**Description:**
Unable to specify VFS parameters value as a registry entry in VFS proxy as follows.
`<parameter name="transport.vfs.FileURI" key="conf:/repository/esb/esb-configurations/test"/>`

**Affected Product Version:**
6.5.0

**Comment by prabushi** [comment]
Registry key support is not available for proxy parameters from the server runtime. Hence, closing the issue.
