### ISSUE TITLE
[6.1.1]You cannot run eclipse by a double click eventhough you have administrator permission

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#34]
[4.1.0]You cannot run eclipse by a double click eventhough you have administrator permission.

You have to either right click and run it as Administrator or Open it

**Comment by sohaniwso2** [comment]
If you are starting Eclipse on Linux, you should launch Eclipse by executing the eclipse binary from the Eclipse directory.

Please refer [1] for more information on starting eclipse on different OS

[1] http://update.se.wtb.tue.nl/documentation/install/manual-starting.html#install-manual-start-eclipse-first-time.

**Comment by prabushi** [comment]
Not reproducible with Integration Studio 7.0.0-M1 release on windows environment. Please reopen the issue if you encounter this issue again.
