### ISSUE TITLE
[Improvement] Increase the window size given to configure the local entry

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#35]
Steps to recreate the **issue**
1. Create ESB Config project
2. Go to local entry and add a local entry

**Observations**
The windows given to add the local entry is too small so that the user has to scroll through the windows to view the content. Better to give the option for the user to increase the windows size as required.

![localentrywndow](https://user-images.githubusercontent.com/14962228/28019156-84e81cb2-659d-11e7-9ec0-739ccc45e86d.png)

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/212/commits/e135cc649395ac11b7016f6b206b75cf6c1c5b80 and https://github.com/wso2/developer-studio/pull/149/commits/02cb4c204774df5e353c6c2c460897c003aba699
