### ISSUE TITLE
Unable to deploy the configured artifacts when creating a Remote Server connection

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#36]
**Environment**
OS - ubuntu 15.10
Java - JDK jdk1.8.0_66
Dev studio with updates (EI611)
Remote Server - Running in windows server 2012 R2

**Steps to recreate the issue**
1. Create a new Remote Server connection with an artefact to deploy 
2. Verify the remote server logs

**Observations**
1. Dev studio shows that the server is started but Remote server connections did not establish

![remoteserverconfig](https://user-images.githubusercontent.com/14962228/28105035-7cc266aa-66fb-11e7-8371-bf4309438aa9.png)

2. Needs to redeploy the artefact to connect to the remote server

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2450
