### ISSUE TITLE
Resources removed through the dev studio did not removed from the remote server

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#37]
Environment
OS - ubuntu 15.10
Java - JDK jdk1.8.0_66
Dev studio with updates (EI611)
Remote Server - Running in windows server 2012 R2

**Steps to recreate the issue**
1. Create a new Remote Server connection with an artefact to deploy
2. Verify that the artefact deployed successfully in the server
3. Remove the resource from the Dev Studio 

![remove1](https://user-images.githubusercontent.com/14962228/28105697-32893052-66fe-11e7-92ca-6844a4c9bdc3.png)

**Observations**
Resource did not remove from the remote server. But removed from the Dev Studio window

![remove2](https://user-images.githubusercontent.com/14962228/28105744-66c91cce-66fe-11e7-9c5f-65455d2cbb81.png)

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2451
