### ISSUE TITLE
[6.1.1]When you Select the project to save artifact it displays an arrow sign to expand

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#38]
[6.1.1]When you Select the project to save artifact it displays an arrow sign to expand

E.g., when you create a proxy as given in the attached screenshot it shows an arrow to expand. But when you click on the arrow it dissapears. This might give a user a wrong understanding.

![screenshot from 2017-07-12 14-36-05](https://user-images.githubusercontent.com/12966170/28110341-b4214f9e-670f-11e7-9095-d117d55b5962.png)

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2478
