### ISSUE TITLE
[6.1.1]When you try to save endpoint in registry, it does not load the available projects

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#39]
[6.1.1]When you try to save endpoint in registry, it does not load the available projects. When you try to save static, it loads. Please see the attachment.

![screenshot from 2017-07-12 14-53-49](https://user-images.githubusercontent.com/12966170/28111190-483f571e-6712-11e7-922a-a898c99b5700.png)

**Comment by ushanib** [comment]
This issue is due to the unavailability of registry project. Can we add more information on this page [1] step 5 3rd point to mention we need to create a registry project and how to create it.

[1] https://docs.wso2.com/display/EI611/Working+with+Endpoints+via+Tooling 


* To save the endpoint in a registry resource project, click Make this a Dynamic Endpoint, click the Browse button next to Save endpoint in and select the registry, and then select the registry (Configuration or Governance) where you want to save the endpoint. Lastly, type the endpoint name in the Registry Path box.

**Comment by praneesha** [comment]
Added the following note in all WSO2 EI versions. For example, see [1].

"For instructions on creating a Registry Resource Project, go to Creating Governance Registry Artifacts."

[1] https://docs.wso2.com/display/EI620/Working+with+Endpoints+via+Tooling
