### ISSUE TITLE
Endpoint (defined inside Send mediator) statistic enabling options are not inline with the EI

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#40]
**Environment**
OS - ubuntu 15.10
Java - JDK jdk1.8.0_66
Dev studio with updates (EI611)
Remote Server - Running in windows server 2012 R2

**Steps to recreate the issue**
1. Create a simple proxy/ sequence with address endpoint defined inside a 'send mediator'. And enable statistics and tracing for address endpoint via Dev Studio
![addressep](https://user-images.githubusercontent.com/14962228/28114751-c7040768-671f-11e7-8a4b-75c08f36b7bf.png)
2. Deploy the proxy/sequence created above in EI

**Observations**
1. Could not find an option to enable statistics and tracing for address endpoint in the Enterprise Integrator UI, when the endpoint is used inside the 'send mediator'. 

Note - If a user created a capp enabling address endpoint statistics and excepting to view the statistics through analytics UI, it is not possible according to the current implementation.

**Comment by sohaniwso2** [comment]
@sashikamw : based on [1], it seems audit status(stats and trace) is supported from synapse level for endpoints.  Can you please double check whether enabling these for endpoints via tooling works fine in analytics UI?  if so this can be an issue with management console UI.

[1] https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/DefaultEndpointFactory.java#L151

**Comment by prabushi** [comment]
Enable statistics and tracing for endpoints is supported via Integration Studio, and the management console will be deprecated with the EI 7.0.0 release. Hence, closing this issue.
