### ISSUE TITLE
[6.1.1]You cannot include 2 mediators in outSequence by drag and drop

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#41]
Create an api or proxy.

Drag a script mediator or property mediator in out sequence.
Now try to drag and drop a send mediator in between 1st mediator and resource. 

![screenshot from 2017-07-12 17-17-21](https://user-images.githubusercontent.com/12966170/28116265-0b14d49a-6726-11e7-8a6b-63a7c5c3168a.png)

When you drag and drop it will display as below screenshot.

![screenshot from 2017-07-12 17-19-00](https://user-images.githubusercontent.com/12966170/28116316-3736128c-6726-11e7-948e-94faad011682.png)

This issue is there vise versa as well. When you have the send mediator and if you try to add another mediator before it, it will not possible to drag and drop.

![screenshot from 2017-07-12 17-24-25](https://user-images.githubusercontent.com/12966170/28116521-0c880648-6727-11e7-9c7e-c76caf9ad6f7.png)

You can include from source view and it will reflect well in design view.

**Comment by sohaniwso2** [comment]
Could not reproduce in EI Tooling 6.3.0 hence reducing the priority

**Comment by prabushi** [comment]
Not reproducible with Integration Studio 7.0.0-M1. Please reopen the issue, if yon encounter this issue again.
