### ISSUE TITLE
Integration Studio doesn't hit the breakpoint if the breakpoint is defined before my remote server is started in the debug mode

### ISSUE THREAD

**Issue by shazni** [wso2/devstudio-tooling-ei#447]
**Description:**
Integration Studio doesn't hit the breakpoint if the breakpoint is defined before my remote server is started in the debug mode.

**Suggested Labels:**
Integration Studio

**Steps to reproduce:**

1. Create a maven multi-module project
2. Under "Debug Configuration" -> "ESB Mediation Debugger" create a new configuration and assign port 9005 for the command port and 9006 for event port 
3. Assign breakpoint in your design view
4. Start the EI with -Desb.debug=true after the previous step (This is important)
5. Call the service 

Breakpoint doesn't hit

If you reverse steps 3 and 4, you'll be able to hit the breakpoint.

**Comment by rosensilva** [comment]
Duplicate issue: https://github.com/wso2/devstudio-tooling-ei/issues/569
