### ISSUE TITLE
[Integration Studio] Drag-and-drop does not work depending on display driver

### ISSUE THREAD

**Issue by praveennadarajah** [wso2/devstudio-tooling-ei#469]
**Description:**
Drag-and-drop does not work depending on the display driver. Following are the behaviours observed

1. When opening directly on laptop, drag-and-drop fails
2. When opening in Hyper-V Windows 10 VM via Hyper-V console, Eclipse works as expected.
3. When opening in Hyper-V VM via Windows Remote Desktop, drag-and-drop fails
4. When opening Eclipse in Hyper-V console THEN connecting to same session via RDP, Eclipse works as expected
5. When opening via RDP then connecting to session via Hyper-V console, drag-and-drop fails.

It all appears to be related to which display drivers are being used as of the moment Eclipse is launched. After Eclipse is launched, drag-and-drop maintains that behavior (works/fails) in relation to that startup environment. 

The above scenario was observed in Microsoft Surface Pro device with default drivers and latest updates via Windows Update.

Windows 10 version:
<img width="488" alt="Screen Shot 2019-06-04 at 10 15 15 AM" src="https://user-images.githubusercontent.com/11292766/58851789-c4c3a400-86b1-11e9-9157-4aad8afc5b1b.png">

Java version:
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by prabushi** [comment]
Related issue https://github.com/wso2/devstudio-tooling-ei/issues/445

**Comment by rosensilva** [comment]
This happens when the OS level zoomig(DPI) level above 150%

**Comment by jrathnayake** [comment]
The workaround for this is to set the scaling to 100%. But when we set scaling to 100% it is very difficult to work with othert applications as it drastically reduces the font.

Appreciate a fix as soon as possible.

**Comment by dakshika** [comment]
@jrathnayake : We tested upto 150%. please check that too

**Comment by joyrathnayake** [comment]
I tested this with Scaling=150 on Windows. It works but the issue is when you change/ reduce the recommended scaling, you can't work with other applications and it reduces the font drastically. 

Is there a way we can fix this to work automatically depending on the current scaling set?

**Comment by rosensilva** [comment]
@joyrathnayake can you please add "-Dswt.autoScale=100" to the IntegrationStudio.ini file as a vmarg

**Comment by joyrathnayake** [comment]
Seems its working. Can we include this in the product distribution itself, so we don't have to add this manually?
