### ISSUE TITLE
Iterator id is defined in dev studio even if the user keeps it blank

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#47]
**Environment**
OS - ubuntu 15.10
Java - JDK jdk1.8.0_66
Dev studio with updates (EI611)
Remote Server - Running in windows server 2012 R2

**Steps to reproduce the issue**
1. Create a proxy including iterate mediator
![iterate1](https://user-images.githubusercontent.com/14962228/28154295-37f5beec-67c7-11e7-942f-d8bc864e3010.png)

**Observations**
```
<inSequence>
            <iterate attachPath="//ser:getQuote" description="" expression="//ser:getQuote/ser:request" **id=""** preservePayload="true" xmlns:ser="http://services.samples">
                <target>
```

**Impact**
If a user created a cApp using an iterator mediator the aggregate mediator without defining the iterator id and aggregator id, aggregate functionality did not work. The reason for the issue is, dev studio define the iterator id as (id = "") which is not inline with the aggregator id.

**Comment by Bhashinee** [comment]
Fixed in 
https://github.com/wso2/devstudio-tooling-esb/commit/d0923858188575a294481bb1ae40afaa02b5807f
