### ISSUE TITLE
[6.1.1] When you select custom proxy, Advance Configuration label should be removed

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#48]
When you select custom proxy, Advance Configuration label should be removed since it does not have anything configurable.

![screenshot from 2017-07-13 17-15-32](https://user-images.githubusercontent.com/12966170/28164932-4058ba62-67ef-11e7-8c0c-e95185c1e1e7.png)

**Comment by Bhashinee** [comment]
Fixed in 
https://github.com/wso2/devstudio-tooling-esb/commit/6890fa7428d02daaae6dcd4170ae955d4bf509ad
