### ISSUE TITLE
[Tooling] Add synapse unit testing framework client 

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/devstudio-tooling-ei#497]
**Description:**
Provide a built-in way to execute a unit test against a given synapse configuration artifact such as sequence, proxy, api, local entry, endpoint.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/989
