### ISSUE TITLE
[6.1.1]When adding new registry, registry path text box is not fully visible or need a horizontal scroller

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#50]
When adding new registry, registry path text box is not fully visible or need a horizontal scroller.

Environment 
========
Fedora 23, JDK 1.8, 6.1.1 Tooling pack with updates

Steps
======
1. Create a XSLT mediator
2. Click on **Properties** window to add **Xslt Static Schema Key**.
3. Add a **schema key** and click on the right corner button to pop up the **Resource Key Editor window**.
4. As given in the screen shot click on the **Create & Point to a new resource** option. 
5. **Registry Path** is not fully visible and there should be a horizontal scroll bar.

![screenshot from 2017-07-13 19-27-16](https://user-images.githubusercontent.com/12966170/28170094-dffd04ee-6801-11e7-9eb3-7eb4ed6fef35.png)

**Comment by Bhashinee** [comment]
Fixed in 
https://github.com/wso2/devstudio-tooling-esb/commit/bc08a775fa0865df30f33aaf68c3654971af51e6
