### ISSUE TITLE
Generate API skeleton from an OpenAPI/Swagger 

### ISSUE THREAD

**Issue by kasun04** [wso2/devstudio-tooling-ei#505]
Support the following use case

- The user needs to create a REST API and she has the swagger definition for the intended API. 
- She uses Swagger definition to create the EI API skeleton. 
- Then she completes the rest of the business logic of the API and deploys it.

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1084 and https://github.com/wso2/devstudio-tooling-platform/pull/235
