### ISSUE TITLE
[6.1.1][Docs]Improvement needed on documentation for Resource Window usage and buttons functionality

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#51]
[Docs] Improvement needed on documentation for Resource Window usage and buttons functionality

E.g., 

1. Create a XSLT mediator
2. Click on Properties window to add Xslt Static Schema Key.
3. Add a schema key and click on the right corner button to pop up the Resource Key Editor window.
4. As given in the screen shot click on the Create & Point to a new resource option.
5. Would be great if documentation  for  **New Resource Window** can be provided for usage of New Resource window 

![screenshot from 2017-07-13 19-27-16](https://user-images.githubusercontent.com/12966170/28170329-b48d6ff0-6802-11e7-936b-b3fda1d0e8dc.png)

If there is already, please provide a link in EI documentation tooling section.

**Comment by praneesha** [comment]
The UIs of Tooling are expected to be self-explanatory, and thereby, the doc strategy does not require this level of information about each and every mediator to be in docs.
