### ISSUE TITLE
Endpoint inside template is not supported - tooling

### ISSUE THREAD

**Issue by tharinduwijewardane** [wso2/devstudio-tooling-ei#516]
Doc: https://docs.wso2.com/display/EI6xx/Sample+752%3A+Load+Balancing+Between+3+Endpoints+With+Endpoint+Templates 

```
    <template name="endpoint_template">
        <parameter name="suspend_duration"/>
        <endpoint name="annonymous">
        <address uri="$uri">
            <enableAddressing/>
                    <suspendDurationOnFailure>$suspend_duration</suspendDurationOnFailure>
        </address>
        </endpoint>
    </template>
```
Following error occurs when the above content is pasted in to source view of a template xml file.

![image](https://user-images.githubusercontent.com/1345465/55244333-045fb100-5267-11e9-80a0-7f14e9d993f4.png)

**Comment by Ibaqu** [comment]
<img width="693" alt="Screen Shot 2019-10-01 at 5 28 34 PM" src="https://user-images.githubusercontent.com/43578935/65959953-f0dd0f00-e470-11e9-8fb1-228bdf40d332.png">
