### ISSUE TITLE
[Improvement] Add 'EnterpriseIntegrator' Server Role when creating a CApp

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#54]
It would be better to Add 'EnterpriseIntegrator' Server Role when creating a CApp via Developer Studio, as the product server role in Enterprise Integrator is 'EnterpriseIntegrator'.

**Comment by sohaniwso2** [comment]
This is fixed at https://github.com/wso2/devstudio-tooling-platform/commit/9f8e06cf84953ebc705a21a980aa9d493ef13100
