### ISSUE TITLE
[6.2.0][Docs]Can we improve EI tooling documentation on below aspects

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#57]
1. Include more screenshots and explain step by step. Because some of the pop up screenshots you get in properties windows are not explained at all

2. Can we include properties windows with explained properties for artifacts?

3. Can we add few samples like overall scenario which can be done using tooling?

**Comment by praneesha** [comment]
These are noted and added to our general continuous improvement efforts on docs.
