### ISSUE TITLE
Scrolling does not work for some mediator properties views

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#573]
**Description:**
Some mediator properties views are not allowed to scroll. eg: connector properties view (connectors)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Fixed in Integration Studio 7.0.0. Please reopen if the issue exists with particular artifact details.
