### ISSUE TITLE
Cannot delete a mock service in unit testing framework

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#577]
**Description:**

1. Create a mock service attaching it to an endpoint. 
2. Use the endpoint in a synapse API
3. Test the API and make sure test passes. 
4. Delete the mock service by right click on the project. It will get removed.

<img width="638" alt="Screen Shot 2019-10-02 at 12 13 14 PM" src="https://user-images.githubusercontent.com/4967046/66023195-0c4a2780-e50e-11e9-9e63-668383777af4.png">

5. Run the test. You will get an exception saying it cannot find the mock service. 
6. Remove the mock service from the test. It will still complain that it cannot find the mock service to delete. 

NOTE: if you refresh, mock service will get removed from the list. But still, test cannot be executed. 

<img width="1012" alt="Screen Shot 2019-10-02 at 12 15 56 PM" src="https://user-images.githubusercontent.com/4967046/66023329-782c9000-e50e-11e9-9a53-6604da0a4e25.png">

**Affected Product Version:**

7.0.0 - alpha 

**OS, DB, other environment details and versions:**    

Mac OS Mojave

**Comment by sajithaliyanage** [comment]
Fixes - https://github.com/wso2/devstudio-tooling-esb/pull/1047
