### ISSUE TITLE
Cannot find version of integration studio in about page 

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#578]
**Description:**

In the about page, there is no information of a version. 

<img width="397" alt="Screen Shot 2019-10-02 at 12 20 41 PM" src="https://user-images.githubusercontent.com/4967046/66023533-14569700-e50f-11e9-917c-edd9bea38667.png">

**Comment by dakshika** [comment]
![carbon-studio-logo](https://user-images.githubusercontent.com/6497326/66030921-05c4ab80-e520-11e9-92f1-01341eff3f9c.gif)
