### ISSUE TITLE
Creation of a blank Drag Placeholder tab when tabs are dragged in Integration Studio

### ISSUE THREAD

**Issue by hadhijawahir** [wso2/devstudio-tooling-ei#586]
**Description:**
The below shown blank drag placeholder is shown when tabs are dragged in Integration Studio.
![Screenshot from 2019-10-03 15-52-00](https://user-images.githubusercontent.com/43289008/66119170-c9637f00-e5f5-11e9-845b-3abd36a8c2ad.png)

**Affected Product Version:**
WSO2 Integration Studio 7.0.0

**Steps to reproduce:**
As shown in the above diagram, when I click on the HealthcareAPI tab and drag it to place it next to any other opened tab (for example next to PineValleyEP tab), then there is a blank new tab that shows up called "Drag Placerholder" which has an error as shown in the above image.

**Comment by rosensilva** [comment]
Fixed in the lastet 720 release
