### ISSUE TITLE
Issue in create ESB project path

### ISSUE THREAD

**Issue by RidmiR** [wso2/devstudio-tooling-ei#592]
**Description:**
Next button is not working when trying to create a new ESB project and after adding additional information. 

**Affected Product Version:**
WSO2 Integration Studio 7.0.0

**OS, DB, other environment details and versions:**  
macos 

**Steps to reproduce:**
Click on create new ESB project
Add the ESB project Name
Click Next and again click on Next

<img width="400" alt="Screen Shot 2019-10-07 at 10 57 49 AM" src="https://user-images.githubusercontent.com/40847371/66286970-66bdfc00-e8f1-11e9-857f-3f6615948237.png">

**Comment by prabushi** [comment]
Duplicate https://github.com/wso2/devstudio-tooling-ei/issues/593
