### ISSUE TITLE
EI Server fails to startup from within developer studio

### ISSUE THREAD

**Issue by nandika** [wso2/devstudio-tooling-ei#6]
WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:
[2017-02-21 05:59:54,148] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24
im getting this error wen i open start EI frm tool
let me know if u hv added any thing new to integrator.sh
or any classpath entry

**Comment by vinok88** [comment]
This is fixed in latest version.

**Comment by Kishanthan** [comment]
Can we make sure that this issue is verified in all operating system environments?

**Comment by vinok88** [comment]
Server startup is verified in MacOS, Linux and Windows.

**Comment by Carlosps** [comment]
Issue still happening in wso2ei-6.1.1
