### ISSUE TITLE
Remove unnecessary server roles in CApp exporter wizard 

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/devstudio-tooling-ei#60]
1. Right click on the CAPP
2. Click on Export Composite Application Project
3. Give destination and click on Next
4. In the next page you can see unnecessary server roles (in the server roles column of the table)

But in the CAPP pom.xml we are supporting to add below roles, hence need to add those to the exporter wizard as well

![aa](https://user-images.githubusercontent.com/6566181/28416873-6593b4a6-6d73-11e7-8893-479297eb25f3.png)

**Comment by Bhashinee** [comment]
Fixed in
https://github.com/wso2/devstudio-tooling-platform/commit/8132592654f40b74385743723b7080422f5b164d
