### ISSUE TITLE
Integrate datamapper mapping models to Integration Studio

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#606]
**Description:**
We need to implement mapping tree model representation for datamapper ML models.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Feature added in - https://github.com/wso2/devstudio-tooling-esb/pull/1080
