### ISSUE TITLE
[Improvement] Implement mandatory field validations 

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#61]
Better to implement mandatory field validations in Dev studio.

For example: When creating  VFS inbound endpoint from management console UI it is mandatory to select 'sequence' and 'on error Sequence', but this validation is not available in the UI, hence user might forget to add these when creating inbound endpoint

**Comment by sohaniwso2** [comment]
please refer https://wso2.org/jira/browse/TOOLS-3039

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/commit/644e07d3a385d85d1a808c3a9635a1f95c33eb86
