### ISSUE TITLE
Issue in data mapper mediator mappings

### ISSUE THREAD

**Issue by chaamini** [wso2/devstudio-tooling-ei#619]
When the data mapper mediator is used to map from csv to json, the actual output column mappings are jumbled. Sample CSV file used to generate mappings is attached
[patientRecords.csv.zip](https://github.com/wso2/devstudio-tooling-ei/files/3782034/patientRecords.csv.zip)

**Comment by krishnilak** [comment]
I am also facing the same issue. 
<img width="1120" alt="dataMapper" src="https://user-images.githubusercontent.com/10182430/69528564-7a521e80-0f94-11ea-9407-e6cca12304dc.png">
