### ISSUE TITLE
Can not use Environment varialbe as URI templates in endpoints

### ISSUE THREAD

**Issue by Vathsan** [wso2/devstudio-tooling-ei#623]
**Description:**
When defining an endpoint URI using an environment variable, the endpoint configuration can not be saved.
The following error occurs,
![image](https://user-images.githubusercontent.com/29911181/68178650-d4258100-ffb2-11e9-8e74-a51ad8330ca0.png)

**Steps to reproduce:**
1. Create an ESB project
2. Create an Endpoint with the following URI template:`$SYSTEM:VAR2`
3. Save the configuration

**Comment by rosensilva** [comment]
Fixed with: https://github.com/wso2/wso2-synapse/pull/1490, https://github.com/wso2/devstudio-tooling-esb/pull/1087
