### ISSUE TITLE
Demonstrate data service creation via dev studio 

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#63]
Demonstrate a sample on creating the basic data service via Developer Studio.

The page [1] does not include any sample on creating a data service via developer studio since the structure of the parameters is different to that of the Management Console UI, it is really important to add a sample with screen shots.

[1] https://docs.wso2.com/display/EI610/Managing+Data+Integration+Artifacts+via+Tooling

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2453
