### ISSUE TITLE
Test framework assert fails when JSON keys of the response are interchanged

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/devstudio-tooling-ei#656]
**Description:**
Test framework asserts should match the incoming - expected JSON payloads despite the order of keys. But it fails when keys are not in order. 

**Suggested Labels:**
Bug

**Affected Product Version:**
7.0

**Comment by sajithaliyanage** [comment]
This is Synapse server side issue. Fixed in - https://github.com/wso2/wso2-synapse/pull/1459
