### ISSUE TITLE
Cannot create maven multiple modules project in Integration studio 7.0

### ISSUE THREAD

**Issue by eiyouwang** [wso2/devstudio-tooling-ei#657]
**Description:**
Creating a new maven multiple modules project failed in integration studio 7.0 latest version, and show no respond or error

**Suggested Labels:**
Integration studio 7.0

**Suggested Assignees:**

**Affected Product Version:**
Download the latest version of Integration studio in https://wso2.com/integration/integration-studio/
try to create a new maven multiple modules project

**OS, DB, other environment details and versions:**    
MacOS Mojave 10.14.6 (18G95)
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Hi @eiyouwang 

This issue is already identified and fixed. Please update the Integration studio to get the fix.

Thanks !

**Comment by prabushi** [comment]
@eiyouwang 
Follow [this] to update the Integration Studio, which is included with the fix for the mentioned issue. (https://docs.wso2.com/display/EI640/Installing+Enterprise+Integrator+Tooling#InstallingEnterpriseIntegratorTooling-UpdateWSO2EITooling)

**Comment by prabushi** [comment]
This issue has been fixed in https://github.com/wso2/devstudio-tooling-ei/issues/595
