### ISSUE TITLE
JAVA_HOME setting cannot change

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/devstudio-tooling-ei#67]
The user cannot change the JAVA_HOME variable which seems to be hard-coded as /home/saminda/software/jdk1.6.0_20 
As a result the carbon server in debian 8.6.0 linux distribution can only be started from command line and not through eclipse creating deployment problems
![screenshot from 2016-11-15 16 15 37](https://cloud.githubusercontent.com/assets/11481059/20338415/a7553e06-abdf-11e6-80c9-79479be06c28.png)
.

**Comment by sohaniwso2** [comment]
originally reported at https://github.com/wso2/devstudio-tooling-platform/issues/4

**Comment by sohaniwso2** [comment]
Steps to get the window in the above issue
1. Add a server
2. Then in the servers window double click on the server, then it will open an editor as shown below. Then click on the 'Open launch configuration'

![gggg](https://user-images.githubusercontent.com/6566181/28815986-d03a8d7e-76c0-11e7-9b0c-5ae55f783eae.png)

**Comment by rosensilva** [comment]
Fixed in the latest Integration Studio 7.0.0 milestone
