### ISSUE TITLE
Add a enableDefaultVariable property to BPMN RestTask

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/devstudio-tooling-ei#691]
**Description:**
There should be tooling support for **enableDefaultVariable** property for BPMN RestTask

**Suggested Labels:**
improvement

**Suggested Assignees:**

**Affected Product Version:**
7.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Duplicate issue https://github.com/wso2/devstudio-tooling-ei/issues/702
