### ISSUE TITLE
Support injecting parameters as environment variable

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#701]
**Description:**
Support https://ei.docs.wso2.com/en/latest/micro-integrator/develop/injecting-parameters/ 
eg: **uri** attribute of an **address endpoint** is not supported via Integration Studio

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1087

**Comment by VirajHasitha** [comment]
We need to fix the tooling to support Injecting Parameters using Environment Variables and Configuration Files in other places where we can inject parameters. 
The $SYSTEM and $FILE prefix can be used to inject parameters in Endpoint parameters, Scheduled Task parameters, Inbound Endpoint parameters, Proxy service parameters.
