### ISSUE TITLE
[DSS] Data source values are not populated when created from Data Service Project

### ISSUE THREAD

**Issue by Nirothipan** [wso2/devstudio-tooling-ei#703]
**Description:**
When we right click on Data Service Project and create a data service ( with data source ), the values are not populated in the UI.

Please refer the screen shot below.

![Screenshot from 2020-02-19 10-06-10](https://user-images.githubusercontent.com/24619763/74802305-7ae22300-52ff-11ea-8f52-74bff258e5f7.png)

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-dss/pull/93
