### ISSUE TITLE
[DSS] Data source values are not persisted when created from data source configs in UI

### ISSUE THREAD

**Issue by Nirothipan** [wso2/devstudio-tooling-ei#704]
**Description:**
Please refer the screen shot below. 
![Screenshot from 2020-02-19 10-07-41](https://user-images.githubusercontent.com/24619763/74802381-b381fc80-52ff-11ea-91de-595e72be4074.png)

Data base engine is missing

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-dss/pull/88
