### ISSUE TITLE
[DSS] Values for test conenction are not populated automatically.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/devstudio-tooling-ei#705]
**Description:**
In Data Source view, even if we have a db url, the values for test connection need to be typed manually.

![Screenshot from 2020-02-19 10-08-41](https://user-images.githubusercontent.com/24619763/74802463-f6dc6b00-52ff-11ea-8b54-876105e1588c.png)

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-dss/pull/142
