### ISSUE TITLE
[DSS] In operations table, button and the table are misplaced

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#708]
In operations table, button and the table are misplaced. 

![image](https://user-images.githubusercontent.com/4967046/74830386-09bf6180-5339-11ea-9801-a2606b292811.png)

**Comment by dilee** [comment]
This is an intermittent issue which occurs sometimes when the web view's rendering happens. Simply refreshing the view will reposition the misplaced elements.
