### ISSUE TITLE
[DSS] Resource path text area is not editable

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#710]
When defining a resource in a data service, cannot add a resource path. Text area is not editable. 
However, figured out that when you click here and there we can get it. 

Reporting the issue, as it is not user friendly. 

![image](https://user-images.githubusercontent.com/4967046/74830802-eea12180-5339-11ea-80ad-6ee3a6ee00d5.png)

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-dss/pull/90
