### ISSUE TITLE
[DSS] When Operation view is extracted both Operation and Resource views are extracted

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#711]
$Subject. Is this the expected behaviour? 
In my view, If clicked on operation view, only that need to be extracted. Usually customers will not use both resources and operations together. 

![image](https://user-images.githubusercontent.com/4967046/74830909-2d36dc00-533a-11ea-8e1b-978cacec963a.png)

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-dss/pull/89
