### ISSUE TITLE
[DSS] When a Resource is edited the view is reset

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#714]
1. Add a resource to Data Service
2. Edit it and click on save. 

![image](https://user-images.githubusercontent.com/4967046/74831640-a420a480-533b-11ea-8f88-0aa7c9aed980.png)

Immediately, the view is reset. Expected behaviour is Resource section will keep open so that the customer can add another resource if he needs. Otherwise it generates too many clicks. 

![image](https://user-images.githubusercontent.com/4967046/74831755-df22d800-533b-11ea-82c0-956875c4677e.png)

This is handled correctly when you add a new query.

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-dss/pull/96
