### ISSUE TITLE
Error when in try to test a MSSQL connection when creating a datasource connection using Integration Studio

### ISSUE THREAD

**Issue by ZanGOlie** [wso2/devstudio-tooling-ei#715]
**Description:**
When I try to 'Test Connection' in the 'Database Configuration' screen an error is thrown

org.osgi.framework.BundleException: Error reading bundle content.
Error reading bundle content.
  java.lang.Thread.getStackTrace(Thread.java:1559)
  org.wso2.developerstudio.eclipse.artifact.dataservice.utils.DependencyProvider.createMultiStatus(DependencyProvider.java:1626)
  org.wso2.developerstudio.eclipse.artifact.dataservice.utils.DependencyProvider.testConnecton(DependencyProvider.java:1325)
  org.wso2.developerstudio.eclipse.artifact.dataservice.utils.DependencyProvider.access$40(DependencyProvider.java:1228)
  org.wso2.developerstudio.eclipse.artifact.dataservice.utils.DependencyProvider$10.handleEvent(DependencyProvider.java:932)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
  org.wso2.developerstudio.eclipse.artifact.dataservice.utils.DependencyProvider.open(DependencyProvider.java:1015)
  org.wso2.developerstudio.eclipse.artifact.dataservice.ui.wizard.NewDataSourceWizardPage$9.widgetSelected(NewDataSourceWizardPage.java:508)
  org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
  org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
  org.eclipse.jface.window.Window.open(Window.java:794)
  org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:99)
  org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
  org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
  org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
  org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
  org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
  org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
  org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
  org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
  org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Affected Product Version:**
Integration Studio 7.0.0

**OS, DB, other environment details and versions:**  
 Windows Server 2016 Datacenter

**Steps to reproduce:**

1. Select an already created Data Service Project in the project navigator, right click and go to New -> Data Service.
2. Select Create New Data Service and click Next.
3. Enter a name for the data service. and click Next
4. Enter DataSource Id -> Select 'MSSQL' from the Database Engine dropdown -> click Configure
5. Select Browse local -> select JDBC file (mssql-jdbc-7.4.1.jre8.jar) -> fill in other details -> click Test Connection

**Comment by sajithaliyanage** [comment]
Fixed in  - https://github.com/wso2/devstudio-tooling-dss/pull/152
