### ISSUE TITLE
Unit test case throws exception while testing a sequence.

### ISSUE THREAD

**Issue by gnvsnaren** [wso2/devstudio-tooling-ei#724]
**Description:**

Unit test suite throw an exception, this test suite is used to test a sequence which accepts a json and gives a json as an output.

 

**Suggested Labels:**

 

**Suggested Assignees:**

 

**Affected Product Version:**

 

**OS, DB, other environment details and versions:**    

Windows 10 pro

Integration Studio 7.0.0

**Steps to reproduce:**

1. Create a sequence.

 

  <?xml version="1.0" encoding="UTF-8"?>

<sequence name="IterateJSON" trace="disable" xmlns="http://ws.apache.org/ns/synapse">

    <property expression="json-eval($)" name="payload" scope="default" type="STRING"/>

    <log>

        <property expression="json-eval($)" name="payload"/>

    </log>

    <property expression="json-eval($.fName)" name="firstName" scope="default" type="STRING"/>

    <log>

        <property expression="get-property('firstName')" name="firstName"/>

    </log>

    

    <payloadFactory media-type="json">

        <format>

           {

            "firstName":"$1"

            }

        </format>

        <args>

            <arg evaluator="xml" expression="get-property('firstName')"/>

        </args>

    </payloadFactory>

    <property expression="json-eval($)" name="payload" scope="default" type="STRING"/>

    <respond/>

</sequence>

2. Create a test suite.

 

<unit-test>

    <artifacts>

        <test-artifact>

            <artifact>/NewSample/src/main/synapse-config/sequences/IterateJSON.xml</artifact>

        </test-artifact>

        <supportive-artifacts/>

        <registry-resources/>

        <connector-resources/>

    </artifacts>

    <test-cases>

        <test-case name="SeqTest">

            <input>

                <payload><![CDATA[{"fName":"Ramu","lName":"Shamu","sex":"male","dob":"08"}]]></payload>

                <properties>

                    <property name="Content-Type" value="application/xml"/>

                </properties>

            </input>

            <assertions>

                <assertEquals>

                    <actual>$body</actual>

                    <expected><![CDATA[{"firstName":"Ramu"}]]></expected>

                    <message>Inside Error message</message>

                </assertEquals>

            </assertions>

        </test-case>

    </test-cases>

    <mock-services/>

</unit-test>

 

3. Run this Test Suite and get below exception

 

[INFO] Test Suite Name: SequenceTest.xml

[INFO] ==============================================

[INFO] Pass Test Cases: N/A

[INFO] Failure Test Cases: N/A

[INFO] 

[INFO] +-------------------+----------------+---------------+---------------+

[INFO] |   TEST CASE       |   DEPLOYMENT   |   MEDIATION   |   ASSERTION   |

[INFO] +===================+================+===============+===============+

[INFO] | Test Case - Suite |    PASSED      |    FAILED     |    SKIPPED    |

[INFO] +-------------------+----------------+---------------+---------------+

[INFO] 

[INFO] Failed Test Case(s): 

[INFO] +---------------------+-------------------+-------------------------------------------------------------------------------------------+

[INFO] |   TEST CASE         |   FAILURE STATE   |       EXCEPTION / ERROR MESSAGE                                                           |

[INFO] +=====================+===================+===========================================================================================+

[INFO] | Test Case - SeqTest |    MEDIATION      | Runtime error occurred while mediating the message                                        |

[INFO] |                     |                   | org.apache.synapse.mediators.AbstractMediator.handleException(AbstractMediator.java:367)  |

[INFO] |                     |                   | org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:139)  |

[INFO] |                     |                   | org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)   |

[INFO] |                     |                   | org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)     |

[INFO] |                     |                   | org.apache.synapse.unittest.TestCasesMediator.sequenceMediate(TestCasesMediator.java:101) |

[INFO] |                     |                   | org.apache.synapse.unittest.TestingAgent.processTestCases(TestingAgent.java:280)          |

[INFO] |                     |                   | org.apache.synapse.unittest.RequestHandler.runTestingAgent(RequestHandler.java:208)       |

[INFO] |                     |                   | org.apache.synapse.unittest.RequestHandler.run(RequestHandler.java:76)                    |

[INFO] |                     |                   | java.lang.Thread.run(Thread.java:748)                                                     |

[INFO] +---------------------+-------------------+-------------------------------------------------------------------------------------------+

[INFO] 

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 13.229 s

[INFO] Finished at: 2020-02-26T16:55:25+05:30

[INFO] Final Memory: 12M/143M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.wso2.maven:synapse-unit-test-maven-plugin:5.2.10:synapse-unit-test (synapse-unit-test) on project NewSample: Exception occurred while running test cases Overall unit test failed -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

 

**Related Issues:**

**Comment by sajithaliyanage** [comment]
This is a known issue in sequence testing. https://github.com/wso2/devstudio-tooling-ei/issues/716. We have fixed this issue and will release this fix in our future release.

**Comment by sajithaliyanage** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1491
