### ISSUE TITLE
Deleting Maven multi module project does not delete inside projects

### ISSUE THREAD

**Issue by dnwick** [wso2/devstudio-tooling-ei#726]
**Description:**
When MMM project contains several child projects and when its deleted from the workspace , it does not delete child projects. Need to delete them manually

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
We have done some improvements for the MMM project creation, import and export. This issue is fixed now.
