### ISSUE TITLE
Changes done from source editor does not reflect/ cause errors when deployed

### ISSUE THREAD

**Issue by dnwick** [wso2/devstudio-tooling-ei#727]
Description:
When changes done via source editor even though the the changes are syntactically correct when the capp is deployed to the server, the content comes removed eg:- call mediator content goes empty comes as ""

As a workaround if we do any changes in source view , we can go to the design view and put a dummy UI element eg:- log full and then change back to source . Then when it deploy it will work most of the time. (this approach also gives same results some time)

We need to fix this ASAP as this is the most preferred way of developers because most people will cut and paste the codes from samples.

Suggested Labels:

Suggested Assignees:

Affected Product Version:

OS, DB, other environment details and versions:

Steps to reproduce:

Related Issues:

**Comment by rosensilva** [comment]
Fixed in the latest release
