### ISSUE TITLE
Add a / by default to an API context

### ISSUE THREAD

**Issue by bsenduran** [wso2/devstudio-tooling-ei#73]
Currently when we create an API, we have to give a context. And there is a validation saying that the context should be starting with `/`.
It will be better instead of validating the `/`, adding a `/` if it is missing. i.e  when a user create an API they can enter a context either starting with or without `/`. When the API is generated it will be append a `/` if it is missing to the context. 
In this way it will be more user friendly

**Comment by Bhashinee** [comment]
Fixed in : https://github.com/wso2/devstudio-tooling-esb/pull/246
