### ISSUE TITLE
'Help Content' directs to the EI 6.5.0 documentation

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/devstudio-tooling-ei#749]
When we click Help -> Help Content, the link takes us to the EI 6.5.0 documentation [1]

<img width="427" alt="Screen Shot 2020-03-05 at 6 53 43 PM" src="https://user-images.githubusercontent.com/21237558/75986361-efc67700-5f13-11ea-96dd-5a8d6658d1b1.png">

Let's direct this to EI 7 latest instead [2].

[1] https://docs.wso2.com/display/EI650/WSO2+Enterprise+Integrator+Documentation
[2] https://ei.docs.wso2.com/en/latest/micro-integrator/develop/WSO2-Integration-Studio/

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-platform/pull/241
