### ISSUE TITLE
Cannot load complex JSON schema as input or output in Datamapper

### ISSUE THREAD

**Issue by arunans23** [wso2/devstudio-tooling-ei#754]
**Description:**

In Datamapper, when a complex JSON schema is loaded, it throws an error.

<img width="783" alt="Screenshot 2020-03-10 at 14 08 25" src="https://user-images.githubusercontent.com/17047910/76294315-9e820300-62d8-11ea-9a52-99531596933d.png">

Schema file 
[patient-schema.json.zip](https://github.com/wso2/devstudio-tooling-ei/files/4311156/patient-schema.json.zip)

 Stack trace found in logs
> !ENTRY org.wso2.developerstudio.datamapper.diagram 4 0 2020-03-10 14:08:22.077
> !MESSAGE Error occurred while opening file.
> !STACK 0
> java.lang.NullPointerException
> 	at org.wso2.developerstudio.datamapper.diagram.custom.util.TreeNodeUtils.getMaxTreeWidth(TreeNodeUtils.java:58)
> 	at org.wso2.developerstudio.datamapper.diagram.custom.util.TreeNodeUtils.getTreeWidth(TreeNodeUtils.java:47)
> 	at org.wso2.developerstudio.datamapper.diagram.edit.parts.InputEditPart.reposition(InputEditPart.java:490)
> 	at org.wso2.developerstudio.datamapper.diagram.edit.parts.InputEditPart.resetInputTreeFromFile(InputEditPart.java:194)
> 	at org.wso2.developerstudio.datamapper.diagram.custom.util.SchemaKeyEditorDialog.saveInputOutputSchema(SchemaKeyEditorDialog.java:1012)
> 	at org.wso2.developerstudio.datamapper.diagram.custom.util.SchemaKeyEditorDialog.openFileBrowser(SchemaKeyEditorDialog.java:994)
> 	at org.wso2.developerstudio.datamapper.diagram.custom.util.SchemaKeyEditorDialog.access$14(SchemaKeyEditorDialog.java:960)
> 	at org.wso2.developerstudio.datamapper.diagram.custom.util.SchemaKeyEditorDialog$4.widgetSelected(SchemaKeyEditorDialog.java:398)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
> 	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1575)
> 	at org.eclipse.swt.widgets.Link.textView_clickOnLink_atIndex(Link.java:793)
> 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6117)
> 	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
> 	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:228)
> 	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1136)
> 	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1128)
> 	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2616)
> 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5799)
> 	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
> 	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:228)
> 	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2148)
> 	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2411)
> 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5863)
> 	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
> 	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5291)
> 	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5441)
> 	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
> 	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3696)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
> 	at org.eclipse.jface.window.Window.open(Window.java:794)
> 	at org.wso2.developerstudio.datamapper.diagram.custom.action.LoadInputSchemaAction.doRun(LoadInputSchemaAction.java:79)
> 	at org.eclipse.gmf.runtime.common.ui.action.AbstractActionHandler.run(AbstractActionHandler.java:359)
> 	at org.eclipse.gmf.runtime.common.ui.action.ActionManager$1.run(ActionManager.java:225)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
> 	at org.eclipse.gmf.runtime.common.ui.action.ActionManager.run(ActionManager.java:223)
> 	at org.eclipse.gmf.runtime.common.ui.action.AbstractActionHandler.runWithEvent(AbstractActionHandler.java:377)
> 	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
> 	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
> 	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Drifftr** [comment]
It seems the JSONSchema file is missing some mandatory attributes such as title and type. After adding those I was able to load the schema without an error. Another thing noticed is this doesn't have any properties or attributes defined, only data type definitions. So in order to list down child nodes in the input box you should have either of them. So shall we refactor[1] the schema file according to the schema?.
[1]. https://json-schema.org/learn/miscellaneous-examples.html
