### ISSUE TITLE
[Windows]Cannot edit already created Data Source through the Design View

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#760]
**Steps to reproduce:**
1. Create a Data source with the following information. 
````
	<config id="101" enableOData="false">
		<property name="driverClassName">com.mysql.jdbc.Driver</property>
		<property name="url">jdbc:mysql://10.100.5.136:3306/Employees
		</property>
		<property name="username">root</property>
		<property name="password">root</property>
	</config>
````
2. Now in the design view, click on edit button. 
Expected: It should be able to go to the edit view. 
Actual: It does not come the pop up.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/146
