### ISSUE TITLE
[Windows]When it is selecting the Datasource type as Carbon Data source, it is asking to select the database engine

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#763]
**Steps to reproduce:**
1. Create a Data Service project and right click on the project and add new Data Service. 
2. Click to add a new data source, insert the below information and click on save. 
Data Source type: Carbon Database
Datasource ID: 100
Datasource name: test

![screen1](https://user-images.githubusercontent.com/31693103/76382166-d1ca9d80-637d-11ea-82f0-c38f849af645.PNG)

It is asked to select a database engine but no drop down to select the database engine.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/141
