### ISSUE TITLE
[Windows]Datasource name is not unique

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#765]
**Steps to reproduce:**
1. Create a Data Service project and right click on the project and add new Data Service.
2. Click to add a new data source, insert the below information and click on save.

- Data Source type: RDBMS
- Datasource ID: 100
- URL: jdbc:mysql://localhost:3306/Employees
- Provide DB credentials

3, Now go to source view and copy paste the same config and save. 
![screen3](https://user-images.githubusercontent.com/31693103/76383381-a77adf00-6381-11ea-8652-0418eb59cfcb.PNG)

Expected: It should not allow to use the same datasource ID.

**Comment by sajithaliyanage** [comment]
Related to the issue - https://github.com/wso2/devstudio-tooling-ei/issues/819
