### ISSUE TITLE
[Windows]Cannot save the Composite Application Project

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#769]
**Description:**
It cannot **Finish** saving Composite Application Project. It hangs at below point. 
![screen5](https://user-images.githubusercontent.com/31693103/76402956-2be15800-63aa-11ea-89d6-69d4058fa813.PNG)

**Steps to Recreate**
1. Create a DataService Project. 
2. Right Click on the created DataService Project and select, new -> other -> Composite Application Project
3. Try to Finish by selecting the relevant project.

**Comment by isuruuy429** [comment]
tested Scenarios
1. The above described scenario

2. Creating a new Composite Application Project from File -> New -> Other and selecting the Data service Project.
Result: Hanging in the middle of the process

3. Creating a new Composite Application Project from File -> New -> Other and without selecting the Data service Project. Ends with below error. 
![Capture5](https://user-images.githubusercontent.com/31693103/76846159-12d31e00-6866-11ea-9da7-2d94a19c41da.PNG)

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/developer-studio/pull/207
