### ISSUE TITLE
[Windows]When a Data Service imported, it does not display the data source details in the Design View. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#770]
**Description:**
When a data service is imported, even though it is displayed the data source details in the source view, once it is switched to Design view and edit data source configurations, it does display the data. 

**Steps to reproduce:**
1. Create a Data Service Project and right click on the project and click on new -> dataservice 
2. Import the following [data service](https://docs.wso2.com/download/attachments/85369899/RDBMSDataService.dbs?version=3&modificationDate=1533117316000&api=v2)
3. Go to the imported data service, click on Data Sources and edit the data source. 

Expected: It should display the details of the Datasource. 
Actual: It does not display the values. 
![screen6](https://user-images.githubusercontent.com/31693103/76410471-fc384d00-63b5-11ea-9008-ad1b33db405e.PNG)

The same behavior with Resources -> edit resource
It does not display the **Resource Method**.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/143
