### ISSUE TITLE
When a query is saved with special characters the record gets created, though it displays as an empty record in the design view. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#771]
**Description:**
Query ID can be saved with special characters and it is displayed in the source view with no errors. Once it comes to the design view it shows as en empty record. 

![screen7](https://user-images.githubusercontent.com/31693103/76411635-360a5300-63b8-11ea-8e74-7f04a6b8cf13.PNG)

![screen8](https://user-images.githubusercontent.com/31693103/76411718-62be6a80-63b8-11ea-878d-4ce84d4c246b.PNG)

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/156
