### ISSUE TITLE
[Windows]Operations: Operation name is not unique. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#774]
**Description:**
It can add the same operation name from the source view. 

**Steps to reproduce:**
1. Create a Data Service Project and right click on the project and click on new -> dataservice
2. Add a datasource, queries and go to Operations Tab. 
3. Add a new Operation, go to source view and copy the same configuration as a new operation. 
It gets added and displayed in the design view as well. 

![screen10](https://user-images.githubusercontent.com/31693103/76493068-c2b81e00-6457-11ea-9b0b-d72014b311e3.PNG)

**Comment by sajithaliyanage** [comment]
Related to the issue - https://github.com/wso2/devstudio-tooling-ei/issues/819
