### ISSUE TITLE
[Windows]Existing data in resources(Resource Method) does not display in Edit mode. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#775]
**Steps to reproduce:**
1. Create a Data Service Project and right click on the project and click on new -> dataservice
2. Create a Data source and a query. 
3, Add a resource with following details. 

- Resource path: Employee/{EmployeeNumber}
- Resource method: GET
- Query: GetEmployeeDetails

4. Now click on Edit button and view the already saved details.
**Expected**: It should display the above entered details. 
**Actual**: Resource Method is not displayed. 
![screen11](https://user-images.githubusercontent.com/31693103/76500235-319c7380-6466-11ea-8577-483f06af384f.PNG)

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/770

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/144
