### ISSUE TITLE
[Windows]MSSQL Database connection cannot be established

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#777]
**Prerequisites**
1. Enable TCP/IP connections for the SQL Server. 
https://docs.wso2.com/display/ESB490/Setting+up+Microsoft+SQL

**Steps to reproduce:**

1. Setup MS SQL Server. 
2. Create Database and a table as below. 

> create database Employees;

> CREATE TABLE Employees (EmployeeNumber Integer NOT NULL, FirstName varchar(255) NOT NULL, LastName varchar(255) DEFAULT NULL, Email varchar(255) DEFAULT NULL, Salary varchar(255));

3. Open Integration Studio and create new Dataservice Project.
4. Create a Datasource with the following information. 
````
Datasource Name: MSSQL
Datasource Type: RDBMS
Database Engine: Microsoft SQL Server
URL: jdbc:sqlserver://localhost:1433;databaseName=Employees
username: <username to login to database>
password: <password>
````
4. In the **Test Connection** field, provide host, port and DB name. Make sure you select RDBMS version as MSSQL version in the dropdown. 

5. Click on **Test Connection**

**Expected**: The connection should be established. 
**Actual**: It is failed to login to the instance.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/152

**Comment by isuruuy429** [comment]
This fix is broken with the new build
https://jenkins-support-ei.wso2.com/jenkins/view/Developer%20Studio/job/devstudio-tooling-ei-weekly-release/

**Comment by isuruuy429** [comment]
[.log](https://github.com/wso2/devstudio-tooling-ei/files/4349619/default.log)
Please find the .log file attached.

**Comment by isuruuy429** [comment]
Seems like the above issue is intermittent, it worked once the Integration Studio was restarted.
