### ISSUE TITLE
[PostgreSQL] Cannot test the connection

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#779]
**Description:**
In the Datasource creation field, in the **Test Connection** section, we have only MySQL, MSSQL, Generic and Derby as the RDBMS versions. 
We need to add the rest of the Database Engine types that we have allowed in the Datasource creation. 

![screen13](https://user-images.githubusercontent.com/31693103/76682196-137a7300-6620-11ea-9a15-b552d0b99d76.PNG)

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/154
