### ISSUE TITLE
It does not contain validation for Data Service Name

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#780]
**Description:**
When you create a new Data Service inside a Data Service Project, it does not have any validation for names that allowed where special characters are allowed. 
As an example we can create something like below. 
````
DataService(4@!#$)
&lt;@#$%&gt;
````

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/164
