### ISSUE TITLE
Cannot connect to Apache Derby Database

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#783]
**Steps to reproduce:**
1. Setup Apache Derby Database[1]
2. Start Apache Derby as a service

> java -jar <DERBY_HOME>/lib/derbyrun.jar server start

3. Create Database Employees and a table, 'Employees'

> CONNECT 'jdbc:derby://localhost:1527/Employees;create=true';  

> create table Employees(ID Integer, firstName varchar(100), lastName varchar(100), salary varchar(50), gender varchar(10));

4. Create a Data Service Project in Integration Studio and add a new Data Service. 
5. Add a new Datasource with the following details, and test the connection. 
<img width="801" alt="Screen Shot 2020-03-16 at 1 26 28 PM" src="https://user-images.githubusercontent.com/31693103/76734896-e3e77a00-6789-11ea-9d25-21eedc9133e1.png">

<img width="753" alt="Screen Shot 2020-03-16 at 1 26 54 PM" src="https://user-images.githubusercontent.com/31693103/76734909-eb0e8800-6789-11ea-9b49-d3925a8bdf40.png">

**Expected**: Connection should be successful. 
**Actual**: Getting an error message as 'Connection failed. Could not connect to database.'

When this was tested against wso2-ei-6.6.0, got the following error. 
> Caused by: java.sql.SQLException: No suitable driver found for jdbc:derby:localhost:1527/Employees

It has been already added the **derby.jar**, **derbyclient.jar**, and **derbynet.jar** from the <DERBY_HOME>/lib/ directory to the <PRODUCT_HOME>/extensions directory as well as <PRODUCT_HOME>/lib directories at two attempts. 

[1] - https://medium.com/ctrl-alt-kaveet/tutorial-installing-apache-derby-4cbf03c4aaba

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/159
