### ISSUE TITLE
[Datasource][Transport settings]Validation for mandatory fields. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#784]
**Description:**
We need to add validations(before saving), at least mark the mandatory fields or provide a warning message to the user when saving. Otherwise, user is allowed to save with parameters. In the end, the added data is lost and the user has to re-add the things. 

**Steps to reproduce:**
1. Create a Data Service project and add a new Data Service. 
2. In Transport Settings, in **Authorization Provider Configuration**, without adding **Authorization Provider Class**, add parameters and Save. 

**Expected**: A warning message needs to be displayed in UI before saving them. 
**Actual**: No warning message or no text can be seen what are mandatory fields. After saving it, once it is switched back to the source view and design view, the added parameters are not saved. Therefore, the user at this point needs to do the rework.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/138
