### ISSUE TITLE
[Datasource][Transport settings]No confirmation message when deleting parameters

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#785]
**Steps to reproduce:**
1. Create a Data Service project and add a new Data Service.
2. In Transport Settings, in **Authorization Provider Configuration**, add **Authorization Provider class** and parameters. 
3. Click on the delete button in front of the parameters. 

**Expected**: A confirmation message to delete the parameters. 
**Actual**: Without confirmation message, the parameter gets deleted.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/170
