### ISSUE TITLE
[Create Datasource]After the validation message, the user entered data and the default data get cleared. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#787]
**Steps to Reproduce:**
1. Create a Data Service project and add a new Data Service.
2. Under the section **Datasources** clieck on **Add new**. 
3. Select MySQL and add the following details. **DO NOT** enter a Datasource ID, and click on Save. 

```
URL: jdbc:mysql://localhost:3306/Employees
Driver: com.mysql.jdbc.Driver
username: root
password: root

```

**Expected**: A warning message should be displayed to enter the Datasource ID. But do not delete the user entered values in the text fields. 
**Actual**: A warning message displayed, and it clears all the data that the user entered as well as the default data such as Driver class.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/141
