### ISSUE TITLE
[Datasource creation]When using alias, make the password text plain

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#788]
**Description**
When the alias is selected while creating a Datasource, the password text is hidden which may imply a wrong impression to the user. 
<img width="798" alt="Screen Shot 2020-03-16 at 3 43 33 PM" src="https://user-images.githubusercontent.com/31693103/76746218-2797af00-679d-11ea-92f8-fa0da26a4d5f.png">

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-dss/pull/138/commits/f0fde402b9251858fc1f324e63d9f5b3bc6d9b2a
