### ISSUE TITLE
[Queries]Query ID is not unique

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#789]
**Description:**
Even though it cannot be added the same queryID from the Design View, it allows to save from the source view and displayed once it is switched back to the Design View. 

**Steps to reproduce:**
1. Create a DataService project and create a Data Service.
2. Create a Datasource. 
3. Create a query, switch to source view, duplicate the same query. 
4. Save above and switch back to the design view. 

**Expected**: The same operation ID should not allow use. 
**Actual**: It is allowed to save through the Source View. 
<img width="1168" alt="Screen Shot 2020-03-16 at 3 55 32 PM" src="https://user-images.githubusercontent.com/31693103/76747138-ae995700-679e-11ea-90b0-eadcc2f21c5f.png">

**Comment by sajithaliyanage** [comment]
Related to the issue - https://github.com/wso2/devstudio-tooling-ei/issues/819
