### ISSUE TITLE
[Queries][Input Mapping]When a non existing Parameter Type and SQL Type is entered from the Source View, it is displayed without any error in the Design View

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#790]
**Description:**
When we create Input Mappings in Queries we have defined set of Parameter Types and SQL Types to select from dropdowns. But if we switch to design view and enter non-existing value, in the Design View it displays without any error. 
These types of situations may occur mistakenly by users in the source view. Therefore, if it has entered non-existing values, it would be better if we can make it blank in the Design View where the user can notice at a glance.  
<img width="1118" alt="Screen Shot 2020-03-16 at 4 20 03 PM" src="https://user-images.githubusercontent.com/31693103/76749234-2f0d8700-67a2-11ea-9346-1afa3f15fc5f.png">

**Comment by sajithaliyanage** [comment]
Related to the issue - https://github.com/wso2/devstudio-tooling-ei/issues/819
