### ISSUE TITLE
It is allowed to save queryId as an empty string through the source view. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#797]
**Description:**
When you add a query from the design view and rename the query Id to an empty string, it is saved in the Design View as an empty Query Id record. 
![Capture3](https://user-images.githubusercontent.com/31693103/76836139-4efe8280-6856-11ea-9f17-58b73ffd025b.PNG)

**Comment by prabushi** [comment]
Related to the issue - https://github.com/wso2/devstudio-tooling-ei/issues/819
