### ISSUE TITLE
Data Service name validation

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#804]
**Description**
Data Service can be created with an empty string and with special characters. 

**Steps to reproduce:**
1. Create a Data Service Project. 
2. Right-click on the project and create a new Data Service. 
3. Create data service with the following names.
- " " (an empty string)
- @@WS#

Expected: A validation warning should pop up. 
Actual: A new Data Service is created.

<img width="1186" alt="Screen Shot 2020-03-18 at 10 24 11 AM" src="https://user-images.githubusercontent.com/31693103/76926539-a78b5980-6902-11ea-9d6f-420b4da8979b.png">

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/164
