### ISSUE TITLE
It does not run with the embedded MI when Data Service Project is asked to run in the MI

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#806]
**Steps to reproduce:**
1. Create a Data Service project with its required sections. 
2. Right-click on the project and select, **Run As** -> **Run on Micro Integrator**

Expected: It should run on the MI without the capp project. 
Actual: It provides the following error message. 
<img width="821" alt="Screen Shot 2020-03-18 at 10 39 35 AM" src="https://user-images.githubusercontent.com/31693103/76927978-3f3e7700-6906-11ea-9120-38fcf852e39c.png">

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-platform/pull/245
