### ISSUE TITLE
Cannot add a CompositeApplicationProject to the Docker Project. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#809]
**Steps to reproduce:**
1. Create a Docker Project, right click and add a Composite Application Project to the Docker project. 
2. Make sure you give **{projectName}CompositeApplicationProject** as the name of the Composite Project. 

Expected: Composite Project is created inside the Docker Project. '
Actual: It returns an error and not created.

**Comment by sajithaliyanage** [comment]
We have fixed the project creation issues from the PRs https://github.com/wso2/developer-studio/pull/207 and https://github.com/wso2/developer-studio/pull/209. 

However, users can not create any type of projects inside a project except Maven Multi-Module(MMM) project. If a user does it, the expected project will create inside the default workspace.
