### ISSUE TITLE
DevStudio fault in space calculation

### ISSUE THREAD

**Issue by srsharon** [wso2/devstudio-tooling-ei#81]
The calculation method for in-sequence and out-sequence, is not logically correct. 
Space allocation should be done only when a mediator is dragged and dropped in the canvas, space should not be allocated unnecessarily.

This screen dump shows the filter mediation without the allocated space.
![image](https://user-images.githubusercontent.com/10986966/30145504-4bbe2c52-93af-11e7-8a3b-2f4d687a2e4e.png)

Once a mediator is dragged it to the filter mediation the out sequence automatically allocates space which in IMO is not necessary 
![image](https://user-images.githubusercontent.com/10986966/30145508-575ee628-93af-11e7-9a7c-742a48916d1c.png)

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2477
