### ISSUE TITLE
Query ID, Resource path and Operation name can be edited

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#812]
**Description:**
It can edit the existing queryID, OperationID and the ResourceID. Ideally it should not be given the option to edit the resourceIdentifier other than editing the rest of the details. 
Further, if the resourceIdentifier is edited, there will be a new query created. 

In Data Sources, it is not allowed to edit the Datasource Identifier. Better if we can follow a consistent pattern.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/175
