### ISSUE TITLE
[Windows] When it is trying to create a Datasource with the same name, it replaces the existing values. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#816]
**Steps to reproduce:**
1. Create a Data Service Project and create a new Data Service. 
2. Create a Datasource with following details. 
```
Datasource identifier: postgres
Database engine: Postgres SQL
URL: jdbc:postgresql://localhost:5432/Employees
username: postgres
password: root
```
3. Now create another Data Source with the same datasource identifier with different details. 
```
Datasource identifier: postgres
Database engine: Postgres SQL
URL: jdbc:postgresql://localhost:5432/Student
username: postgres1
password: root
```

**Expected**: It should not allow to save another data source with the same name at the creation step itself. 
**Actual**: It replaces the data in the existing data source without any warnings.

**Comment by sajithaliyanage** [comment]
In the updated DSS Editor, User can not create a Datasource with an already exists Datasource name.

**Comment by isuruuy429** [comment]
This issue happens in Datasources, Queries, Operations, Output Parameters.
