### ISSUE TITLE
[Datasource type: CSV]Asking for a SQL Query

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#823]
$subject which not necessary, since it is mandatory cannot proceed further without providing a SQL query. 

![Capture](https://user-images.githubusercontent.com/31693103/77067493-0805be00-6a0b-11ea-892b-e67132c330e4.PNG)

Please refer in EI 6.6.0
https://docs.wso2.com/display/EI640/Exposing+CSV+Data+as+a+Data+Service

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-dss/pull/183
