### ISSUE TITLE
[Datasource Type: MongoDB]Mark the mandatory fields

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#826]
**Description:**
Since it has quite a set of values to be filled, it would be better if we can mark the mandotory parameters in the UI. 

![Capture](https://user-images.githubusercontent.com/31693103/77097376-b4a96500-6a36-11ea-98c5-ee4da25a1687.PNG)

**Comment by prabushi** [comment]
Mandatory fields are marked in Red, in the latest distribution.
![Screenshot from 2020-03-20 13-14-30](https://user-images.githubusercontent.com/5234623/77144891-0d1b4980-6aad-11ea-8b94-b45509d36ce6.png)
