### ISSUE TITLE
[H2] - Test Connection does not pick the version

### ISSUE THREAD

**Issue by isuruuy429** [wso2/devstudio-tooling-ei#828]
**Description:**
When we switch to the H2, in the test connection section, it does not pick the H2. 
![Capture](https://user-images.githubusercontent.com/31693103/77137054-44303180-6a92-11ea-9568-98a4a746a793.PNG)

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-dss/pull/185
