### ISSUE TITLE
Integration Studio is too slow to render graphical view

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#843]
**Description:**

1. Create a WSO2 Integration Studio project and add the attached source. 
2. Change something on the source and click on design view. 

You will notice it takes a lot of time to render. For a developer, practically, this gives a negative feeling about the performance of Integration Studio. 

Please see below attached video at [1]. 

[1]. https://drive.google.com/file/d/1-h53cqrOaLFZ_xwwb1bz9wVk7yLhbP9x/view?usp=sharing
[s3-connector-project.zip](https://github.com/wso2/devstudio-tooling-ei/files/4373458/s3-connector-project.zip)

**Comment by abeykoon** [comment]
[s3-connector-project.zip](https://github.com/wso2/devstudio-tooling-ei/files/4373464/s3-connector-project.zip)

Please find the project attached.

**Comment by abeykoon** [comment]
Any specific improvements done over this?

**Comment by DMadhuranga** [comment]
We came across a code block that takes some extraneous steps to read certain elements from an XML file. Once it was replaced with some a simpler one, execution time was reduced by 70%.

**Comment by abeykoon** [comment]
Great. Thanks for the update!
