### ISSUE TITLE
EI Developer Studio screens are not visible properly 

### ISSUE THREAD

**Issue by Amandakothalawala** [wso2/devstudio-tooling-ei#85]
In windows 10, some of the screens cannot be viewed properly. Please refer attached images below and there are no horizontal/vertical scroll bars or minimize/maximize feature either. 

![1](https://user-images.githubusercontent.com/6723443/30469446-fe20b978-9a0d-11e7-83be-5642ee510f54.PNG)
![2](https://user-images.githubusercontent.com/6723443/30469448-fe67c26e-9a0d-11e7-8cf4-1bdbe1985bcb.PNG)
![3](https://user-images.githubusercontent.com/6723443/30469447-fe5481d6-9a0d-11e7-9651-aa34d7a4aa03.PNG)

**Comment by SangeethKarunaratne** [comment]
Can Reproduce

**Comment by rosensilva** [comment]
Fixed in the latest Integration Studio 7.0.0 Milestone 1
