### ISSUE TITLE
Imply that the endpoint name is getting extended when it is too long

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#86]
Currently endpoint name is getting cutoff at the container width. But, full endpoint name is visible at the properties pane. Better to imply as "..." at the end of endpoint name in the diagram.

![endpoint](https://user-images.githubusercontent.com/5234623/30534353-7a8c0020-9c7b-11e7-8bb9-e1644339379c.png)

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2455
