### ISSUE TITLE
List deployed services in embedded MI when server started

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#884]
**Description:**
In order to improve the user experience we have to list down any deployed services in embedded MI. Otherwise its hard for the user to find the service url to call. Suggestion - Embed MI CLI tool

**Comment by abeykoon** [comment]
Can we embed the dashboard itself in tooling? (like we did for Connector browsing)? 
Otherwise with feature changes we will need to maintain these as well.

**Comment by abeykoon** [comment]
Also we need to document this feature.

**Comment by prabushi** [comment]
Created [this](https://github.com/wso2/devstudio-tooling-ei/issues/986) issue to track the documentation task.
