### ISSUE TITLE
Embed new MI 1.2.0 into Integration Studio

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#887]
**Description:**
Embed latest MI 1.2.0 into Integration studio.

**Comment by prabushi** [comment]
Fixed with the following PRs.
https://github.com/wso2/devstudio-tooling-platform/pull/261
https://github.com/wso2/devstudio-tooling-platform/pull/262
https://github.com/wso2/devstudio-tooling-esb/pull/1124
https://github.com/wso2/devstudio-tooling-ei/pull/1002
