### ISSUE TITLE
Cannot import project with conectors

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#896]
**Description:**

1. Create an Integration project with Google firebase. Add connector exporter and composite application projects as well. Import the connector and use its operations in an API. 
2. Remove `.tmp` and `.metadata` folders from repo. This step is needed as there is a lot of files not relevant to the source I want to pack and send over.
3.  Close the studio and start it pointing to a different workplace. 
4. Import the earlier projects as below. 
![image](https://user-images.githubusercontent.com/4967046/78778065-4530f080-79b8-11ea-9c6c-eb71a66e5ef2.png)

5. You will see in API there are errors. When clicked on it, all the configuration is lost!!

![image](https://user-images.githubusercontent.com/4967046/78778126-62fe5580-79b8-11ea-9c2a-9e97ee038b76.png)

**Affected Product Version:**

7.0.2

**OS, DB, other environment details and versions:**

**Comment by Drifftr** [comment]
This happens due to connector not available in the workspace when project which uses the connector is imported. Adding the connector before importing this will solve the issue. Possible duplicate - https://github.com/wso2/devstudio-tooling-ei/issues/897
