### ISSUE TITLE
Cannot load workplace back without hidden files

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#897]
**Description:**

1. Create an Integration project with Google firebase. Add connector exporter and composite application projects as well. Import the connector and use its operations in an API.

2. Remove .tmp and .metadata folders from repo. 

3. Close the studio and start it pointing to the same workplace. 

Non of the projects are visible. Is it mandatory to ship these folders with the workplace to make workplace meaningful? 

If that is the case, what is the correct way to export and import a set of related projects? 
(integration project + connector exporter project + composite application project)

**Comment by Drifftr** [comment]
If we are importing a connector based project we need to add the connector to workspace first. This can be added New-> Project -> Add/Remove Connectors. However this has an extra overhead to the user. So created a new issue for this improvement.
Issue - https://github.com/wso2/devstudio-tooling-ei/issues/901
