### ISSUE TITLE
Provide help option with mediator parameters in properties pane

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#90]
Related implementation 
- https://github.com/wso2/devstudio-tooling-bps/commit/deeca4079a411e096eed6eebb9f93ed57f5e8cc6#diff-7ff95daa7a29086bddb6917d09e1df21
- https://github.com/NatashaWso2/devstudio-tooling-bps/commit/4e82ab3c6f327868b5cde81bc1727fafe4cc281b

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/product-ei/issues/2457
