### ISSUE TITLE
ESB Tooling sequence editor's source view gets empty when an exception occurs in design view

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#92]
**Description:**
The source view of the ESB tooling editor gets empty when an error occurs in design view. This happens when we switch to the source view from the design view.

**Suggested Labels:**
ESB-Tooling, Sequence Editor

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a proxy service.
2. Do something which causes an exception in design view (Adding a datamapper without a config).
3. Switch to source view.
 A error message will be displayed and the source view will be empty.

**Related Issues:**

**Comment by prabushi** [comment]
Enabled option to rollback the synapse configurations at switching views in https://github.com/wso2/devstudio-tooling-esb/commit/460ac0c89786371ce9aed6a9e97340fa875aea04
