### ISSUE TITLE
[Connector] Revamp connector parameter 

### ISSUE THREAD

**Issue by milindaperera** [wso2/devstudio-tooling-ei#929]
**Description:**
Revamp the connector configuring improving UX.
<img width="1374" alt="Screenshot 2020-04-21 at 00 48 41" src="https://user-images.githubusercontent.com/7402364/79790950-26443e00-836a-11ea-8453-1a136404ecdf.png">

1. Should be easy to handle large list of parameters. So area dedicated for parameters should be large.
2. Ability to provide expressions in same view without popups per each parameter 
3. Reduce number of popups to configure parameters.

Combine parameter view with expression view
<img width="1385" alt="Screenshot 2020-04-21 at 00 49 34" src="https://user-images.githubusercontent.com/7402364/79791019-4247df80-836a-11ea-8414-e849f8fa426c.png">

Remove this intermediate popup
<img width="968" alt="Screenshot 2020-04-21 at 00 50 18" src="https://user-images.githubusercontent.com/7402364/79791071-568bdc80-836a-11ea-8249-7fec41a05b59.png">

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1216
