### ISSUE TITLE
Datamapper Input & output boxes are scrolled out of the view

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/devstudio-tooling-ei#933]
When the DataMapper config is opened for the first time, Datamapper Input and output boxes are scrolled up. The canvas looks like empty.

![Screenshot from 2020-04-24 06-11-36](https://user-images.githubusercontent.com/25482980/80163226-1db26880-85f3-11ea-8102-d03091cbb56c.png)

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-esb/pull/1119
