### ISSUE TITLE
Update BPMN Soap task with service reference (EPR)

### ISSUE THREAD

**Issue by prabushi** [wso2/devstudio-tooling-ei#94]
**Description:**
Update documentation according to the fix done at https://github.com/wso2/devstudio-tooling-bps/pull/33
Related doc link: https://docs.wso2.com/display/EI620/Invoking+a+BPMN+SOAP+Endpoint

**Affected Product Version:**
EI tooling 6.2.0

**OS, DB, other environment details and versions:**    
JDK 8

**Steps to reproduce:**
N/A

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/93

**Comment by praneesha** [comment]
Added a row to the table for the Service EPR and updated the screenshot in [1].

This is applicable from WSO2 EI 6.2.0 onwards.

[1] https://docs.wso2.com/display/EI620/Invoking+a+BPMN+SOAP+Endpoint
