### ISSUE TITLE
[Integration Studio] AI generated data mapping is getting removed automatically

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/devstudio-tooling-ei#952]
**Description:**
When AI generated data mapping is used, the mapping gets removed automatically when re-open the file.

**Affected Product Version:**
7.0.2

**Steps to reproduce:**
1. Add a datamapper.
1. Load input and output schema.
1. Perform AI based data mapping
1. Close the file and open it again.
1. The mapping is removed.

**Comment by Nirothipan** [comment]
I also faced this, please consider fixing this

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/devstudio-tooling-esb/pull/1119
