### ISSUE TITLE
Validations are not working when creating a new API with a swagger definition

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/devstudio-tooling-ei#960]
**Description:**
In the Integration Studio, we can create an API with a swagger definition. However, it throws NPE if the swagger definition is not in the correct format. We need to handle this tooling itself. Also, in **Create new API** wizard we can create an API without pointing a swagger definition file. It always enables the **Finish** button in the wizard to create an API.  

**Suggested Labels:**
Type/Bug

**Comment by rosensilva** [comment]
Fixed
