### ISSUE TITLE
Artifacts disappeared with a config error

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#97]
**Description:**
All mediator config disappeared from design view and also from source view after some error occurred. 
**Suggested Labels:**

**Suggested Assignees:**
@prabushi 

**Affected Product Version:**
3.8.0 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Define an Oauth mediator
2. In properties place https://localhost:9444/services/ 
3. *some* error happened when saving the config
4. After that, model is not working. Design view and source view is not synced. But, all the configs were there in the original file in file system. 

Only way to get out of issue was to restart eclipse. 

**Related Issues:**
N/A

**Comment by prabushi** [comment]
Similar issue https://github.com/wso2/devstudio-tooling-ei/issues/92

**Comment by sohaniwso2** [comment]
Are you getting any error dialog? Could you please share the error log at <workspace>.metadata/.log

**Comment by prabushi** [comment]
Not reproducible with Integration Studio 7.0.0-M1. 
Please reopen if you encounter this issue again.
