### ISSUE TITLE
The AI Generated Mappings Available is not visible enough.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/devstudio-tooling-ei#979]
**Description:**
This is a nice feature but due to the zoom issues in the studio, the button is not visible enough and we need to scroll to find it out.

Kindly considering making it visible somehow so that people who aren't already aware of this doesn't miss this feature.

We can move it to below try it out icon since it is big and visible.

![Screenshot from 2020-05-16 21-55-25](https://user-images.githubusercontent.com/24619763/82124922-07e22e80-97c0-11ea-9813-c70dd6c72716.png)

**Comment by sajithaliyanage** [comment]
We have set the auto-focus event to this **Apply** button for making it visible all the time when a user loads new input or output schema via the data mapper editor.
