### ISSUE TITLE
Add QoS Parameter support to Developer Studio 

### ISSUE THREAD

**Issue by abeykoon** [wso2/devstudio-tooling-ei#98]
**Description:**
Add following parameter support for RabbitMQ Inbound EP configurations

`<parameter name="rabbitmq.channel.consumer.qos">1</parameter>` 

**Affected Product Version:**
3.8.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Drifftr** [comment]
Already fixed with https://github.com/wso2/devstudio-tooling-esb/pull/198/

**Comment by Niranjan-K** [comment]
@Drifftr : Can you point me to a blog or doc on how to achieve this?
