### ISSUE TITLE
AI Mapping isn't displayed properly in UI

### ISSUE THREAD

**Issue by Nirothipan** [wso2/devstudio-tooling-ei#982]
**Description:**
When Mapped it gives the following output

![Screenshot from 2020-05-18 18-49-50](https://user-images.githubusercontent.com/24619763/82219137-7cd97380-993a-11ea-8755-cd88fc7455eb.png)

which gives an impression that the mapping is not correct , but when expanded it shows it correctly.

![Screenshot from 2020-05-18 19-02-40](https://user-images.githubusercontent.com/24619763/82218872-2b30e900-993a-11ea-87d0-e9784425a8c4.png)

Input JSON
```json
{ "name": "John Doe",
  "dob": "1990-03-19",
  "ssn": "234-23-525",
  "address": "California",
  "phone": "8770586755",
  "email": "johndoe@gmail.com",
  "doctor": "thomas collins",
  "hospital": "grand oak community hospital",
  "cardNo": "7844481124110331",
  "appointment_date": "2025-04-02"
}
```
Output JSON
```json
{
  "patient": {
    "name": "John Doe",
    "dob": "1990-03-19",
    "ssn": "234-23-525",
    "address": "California",
    "phone": "8770586755",
    "email": "johndoe@gmail.com"
  },
  "doctor": "thomas collins",
  "hospital": "grand oak community hospital",
  "appointment_date": "2025-04-02"
}
```

**Comment by sajithaliyanage** [comment]
To fix this issue we have increased the gap between input and output boxes.
