### ISSUE TITLE
ConfigMapper plugin not getting executed inside the MMM

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/devstudio-tooling-ei#987]
**Description:**
$subject. ConfigMapper plugin does not execute when user run `mvn clean install` command inside the MMM project. It says, either deployment.toml path or template path is invalid. 

**Suggested Labels:**
Type/Bug

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/maven-tools/pull/68 and https://github.com/wso2/devstudio-tooling-platform/pull/267.
