### ISSUE TITLE
Not possible to uncheck 'Copy Projects into workspace' when importing existing WSO2 Project

### ISSUE THREAD

**Issue by PetteriPertola** [wso2/devstudio-tooling-ei#994]
**Description:**
When using the latest version of WSO2 Integration Studio, and trying to import an existing wso2 project, it is not possible to uncheck the box **'Copy projects into workspace'. The box is grayed out.**

This means that for example source control is no longer working as the changes are not being made on the project in the source control but on a completely separate project that is not tracked by the source control!

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** WSO2 Integration Studio v 7.0.2

**OS, DB, other environment details and versions:**    
Windows 10 64bit 

**Steps to reproduce:**
Click file -> import -> choose existing WSO2 projects

**Related Issues:**

**Comment by arunans23** [comment]
This has been fixed with an update. Please take the latest update and you will be able to check the  box. 
Steps :
1. Open Integration Studio
2. Help --> Check for Updates. Then install the available updates.

**Comment by PetteriPertola** [comment]
Thank you. 
Is this available on the latest download from the main site as well?
The updater isn't working for me due to internal company firewall settings.

**Comment by rosensilva** [comment]
Then you should wait for the next release which is expected in the coming two or three months. The updater tool is used to deliver the updates between releases.
