### ISSUE TITLE
Data mapper doesn't allow uploading/choosing CSV as an input file format on Mac

### ISSUE THREAD

**Issue by wx-yz** [wso2/devstudio-tooling-ei#996]
**Description:**
Data mapper doesn't allow loading a CSV file as input format from file system on Mac.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio latest

<img width="690" alt="Screen Shot 2020-05-26 at 10 49 06 AM" src="https://user-images.githubusercontent.com/57770159/82933574-f676f000-9f3e-11ea-925f-e36ae10853c0.png">

**OS, DB, other environment details and versions:**    
macOS Catalina 10.15.4

**Steps to reproduce:**
1. Start project from new template, File Transfer
2. Open StudentDataFileProcessingSeq and drag a new data mapper from Mediator palette
3. Double click and create a new data mapper project
4. Scroll up until you see input / output section
5. Load a .csv file as input

Nothing happens. Doesn't load anything, it shows the upload dialog again. Works for XML and JSON. Only happens on the Mac.

**Comment by vanjikumaran** [comment]
A similar issue has been reported https://github.com/wso2/devstudio-tooling-ei/issues/965

**Comment by prabushi** [comment]
Duplicated https://github.com/wso2/devstudio-tooling-ei/issues/928
