### ISSUE TITLE
Data mapper config not visible in Windows unless High DPI scaling override is enabled

### ISSUE THREAD

**Issue by wx-yz** [wso2/devstudio-tooling-ei#997]
**Description:**
When trying to create a new data mapper config in Windows it doesn't let complete that action. In the config window there's no option to create a project. That window is not resizable as well.

![dev-studio-datamapper-not-visible](https://user-images.githubusercontent.com/57770159/82940977-73f42d80-9f4a-11ea-906c-439ba8e00336.png)

In order to get past this, I had to enable High DPI scaling. The problem is, without this option, everything else (what I've tried so far) seems to be working. Only this dialog box had the problem. Can we maybe put this into the documentation so that if someone is having the same issue this can be used as a workaround?

![turn-on-hidpi-scaling](https://user-images.githubusercontent.com/57770159/82941123-ae5dca80-9f4a-11ea-95a2-055fdcd4ded7.png)

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio latest

![image](https://user-images.githubusercontent.com/57770159/82941275-f381fc80-9f4a-11ea-9e0c-df000d0982c1.png)

**OS, DB, other environment details and versions:**   
Windows 10

**Comment by prabushi** [comment]
This issue is already fixed in the latest updates (Duplicated [issue](https://github.com/wso2/devstudio-tooling-ei/issues/851). You need to update the Integration studio and remove **-Dswt.autoScale=100** from the IntegrationStudio/IntegrationStudio.ini file.
