### ISSUE TITLE
Integration Studio open window tabs doesn't draw correctly with default WSO2 EI theme. Classic theme works well

### ISSUE THREAD

**Issue by wx-yz** [wso2/devstudio-tooling-ei#998]
**Description:**
Default WSO2 EI theme doesn't render current open tabs correctly. Here's a video of the issue,

![ei-menu](https://user-images.githubusercontent.com/57770159/82941975-224ca280-9f4c-11ea-97f2-2e70bd2f714d.gif)

If I switch to classic theme, then it renders correctly without any artifacts.

**Affected Product Version:**
Integration Studio latest

![image](https://user-images.githubusercontent.com/57770159/82942127-53c56e00-9f4c-11ea-9f11-096e0ab4fcf7.png)

**OS, DB, other environment details and versions:**    
Windows 10

**Comment by tharakamd** [comment]
This issue is fixed in the v7.1.0-beta version. Tested in Windows 10 Pro with the new theme.
